import type { AnswerKey } from "./diagnostic";

export const PRACTICE_EXPANSION_ANSWER_KEY: AnswerKey = {
  "practice-num-24": { correctIndex: 2, explanation: "The differences increase by 5 each time: 5, 10, 15, 20, then 25. Adding 25 to 64 gives 89." },
  "practice-num-25": { correctIndex: 2, explanation: "The successive increases are consecutive squares: 4, 9, 16, 25, and 36. Adding 36 to 56 gives 92." },
  "practice-num-26": { correctIndex: 1, explanation: "A 25% discount leaves $120. Reducing that amount by another 10% leaves $108." },
  "practice-num-27": { correctIndex: 2, explanation: "The decrease is 60. Dividing 60 by the original 250 gives 0.24, or 24%." },
  "practice-num-28": { correctIndex: 3, explanation: "Each worker packs 12 boxes per hour. Eight workers working five hours pack 8 times 5 times 12, or 480 boxes." },
  "practice-num-29": { correctIndex: 3, explanation: "The train travels 72 miles per hour because 180 divided by 2.5 is 72. In four hours it travels 288 miles." },
  "practice-num-30": { correctIndex: 1, explanation: "Red cards make up 3 of 8 ratio parts. Three eighths of 64 is 24." },
  "practice-num-31": { correctIndex: 3, explanation: "The recipe uses one eighth cup per roll. Multiplying 30 by one eighth gives 3.75, or 3 3/4 cups." },
  "practice-num-32": { correctIndex: 2, explanation: "Six numbers averaging 24 total 144. Subtracting the known total of 109 leaves 35." },
  "practice-num-33": { correctIndex: 3, explanation: "The original total is 12 times 78, or 936. The new total is 13 times 80, or 1,040, so the added score is 104." },
  "practice-num-34": { correctIndex: 2, explanation: "Subtracting 2x and adding 7 gives 2x equals 26, so x equals 13." },
  "practice-num-35": { correctIndex: 2, explanation: "Expanding gives 3x minus 10 equals 2x plus 9. Subtracting 2x and adding 10 gives x equals 19." },
  "practice-num-36": { correctIndex: 3, explanation: "The month-to-month changes are 12, 16, minus 3, 27, and 13. The largest increase leads into May." },
  "practice-num-37": { correctIndex: 2, explanation: "The four teams produced 200 units in total. Team C produced 50, and 50 out of 200 is one fourth." },
  "practice-num-38": { correctIndex: 4, explanation: "Alpha and Gamma each cost $3,000 per task. Beta costs $4,000 and Delta costs $3,500 per task." },
  "practice-num-39": { correctIndex: 2, explanation: "Twenty-four pens cost $36 using the three-pack and $32.40 using the eight-pack. The better offer saves $3.60." },
  "practice-num-40": { correctIndex: 3, explanation: "The second number is the square of the first. Seven squared is 49, so twelve squared is 144." },
  "practice-num-41": { correctIndex: 3, explanation: "The rule squares the first number and adds 3. Five squared plus 3 is 28, and eight squared plus 3 is 67." },
  "practice-ver-22": { correctIndex: 1, explanation: "A glove is worn on a hand in the same way that a shoe is worn on a foot." },
  "practice-ver-23": { correctIndex: 2, explanation: "A blueprint provides instructions for making a building; a recipe provides instructions for making a meal." },
  "practice-ver-24": { correctIndex: 1, explanation: "Ephemeral contrasts with permanent, and erratic contrasts with steady." },
  "practice-ver-25": { correctIndex: 1, explanation: "Mitigate means to make something less severe. Aggravate means to make it more severe." },
  "practice-ver-26": { correctIndex: 2, explanation: "Sporadic means occurring irregularly or occasionally. Continuous is its closest opposite." },
  "practice-ver-27": { correctIndex: 2, explanation: "Docile means compliant or easily managed. Defiant expresses the opposite behavior." },
  "practice-ver-28": { correctIndex: 1, explanation: "A coherent account is logically ordered and consistent, which allows investigators to verify the sequence." },
  "practice-ver-29": { correctIndex: 2, explanation: "A proposal based on impossible assumptions cannot be defended or sustained, so untenable best fits." },
  "practice-ver-30": { correctIndex: 0, explanation: "The phrase far from signals contrast. A policy adding unexpected restrictions is the opposite of lenient." },
  "practice-ver-31": { correctIndex: 4, explanation: "Infer, deduce, conclude, and presume involve forming a judgment. Observe means directly noticing something." },
  "practice-ver-32": { correctIndex: 4, explanation: "A sonnet, novel, essay, and biography are authored compositions. A dictionary is primarily a reference work." },
  "practice-ver-33": { correctIndex: 4, explanation: "Impartial, neutral, objective, and disinterested all indicate lack of bias. Biased is their opposite." },
  "practice-ver-34": { correctIndex: 2, explanation: "Only R9K-3164 is identical on both sides. Every other pair changes or transposes at least one character." },
  "practice-ver-35": { correctIndex: 3, explanation: "The first, third, and fifth record pairs match exactly, for a total of three matching pairs." },
  "practice-ver-36": { correctIndex: 2, explanation: "Lucid means clear and understandable. Obscure is the closest opposite." },
  "practice-ver-37": { correctIndex: 2, explanation: "A thermometer measures temperature, while a barometer measures atmospheric pressure." },
  "practice-ver-38": { correctIndex: 1, explanation: "Equivocal means ambiguous or open to multiple interpretations, matching a response that reveals no clear intention." },
  "practice-log-13": { correctIndex: 1, explanation: "The alphabet jumps increase from 3 through 7 letters: C to F, J, O, U, then B after wrapping past Z." },
  "practice-log-14": { correctIndex: 0, explanation: "The first letters move backward by two while the second letters move forward by two, producing RI." },
  "practice-log-15": { correctIndex: 0, explanation: "Every Ren is a Tal, and no Tal can be a Vek. Therefore no Ren can be a Vek." },
  "practice-log-16": { correctIndex: 1, explanation: "The Kems that are Lods must also be Pivs because every Lod is a Piv. Thus some Kems are Pivs." },
  "practice-log-17": { correctIndex: 0, explanation: "The Huks that are Fars cannot be Gims because no Far is a Gim. Therefore some Huks are not Gims." },
  "practice-log-18": { correctIndex: 4, explanation: "Nia is before Omar and Pia, while Raj is before Pia. Nothing establishes whether Nia or Raj is earlier." },
  "practice-log-19": { correctIndex: 3, explanation: "The stated relationships force J before K before M before N, so J, K, and M must all precede N." },
  "practice-log-20": { correctIndex: 1, explanation: "If a set alarm guarantees blinking, the absence of blinking means the alarm was not set. This is the contrapositive." },
  "practice-log-21": { correctIndex: 2, explanation: "Urgency is sufficient for same-day review but not necessary. A report reviewed today may or may not be urgent." },
  "practice-log-22": { correctIndex: 0, explanation: "Moving F, I, S, and H forward two alphabet places produces H, K, U, and J: HKUJ." },
  "practice-log-23": { correctIndex: 0, explanation: "Reversing TEAM gives MAET. Moving its first letter M forward one place changes it to NAET." },
  "practice-log-24": { correctIndex: 3, explanation: "Eight, 27, 64, and 125 are consecutive integer cubes. One hundred is not a cube." },
  "practice-log-25": { correctIndex: 3, explanation: "A Wednesday meeting would require Monday training, which is excluded. Tuesday training therefore places the meeting on Thursday." },
  "practice-log-26": { correctIndex: 2, explanation: "Letter jumps grow by one: plus 3, 4, 5, then 6 gives T. The numbers double, so 16 becomes 32." },
  "practice-spa-13": { correctIndex: 2, explanation: "Turning 135 degrees clockwise from north passes northeast and east and ends at southeast." },
  "practice-spa-14": { correctIndex: 2, explanation: "Southeast is 135 degrees clockwise from north. Moving 225 degrees counterclockwise ends at west." },
  "practice-spa-15": { correctIndex: 3, explanation: "Northeast becomes southeast, then east, then west after the three successive turns." },
  "practice-spa-16": { correctIndex: 1, explanation: "A vertical mirror reverses the left-to-right order, so 2B7 appears in the order 7B2." },
  "practice-spa-17": { correctIndex: 1, explanation: "Reflection across a horizontal line reverses vertical direction, so an upward arrow points down." },
  "practice-spa-18": { correctIndex: 3, explanation: "The arrow rotates 90 degrees clockwise each step: up, right, down, then left." },
  "practice-spa-19": { correctIndex: 1, explanation: "The turns alternate 90 and 180 degrees clockwise. After returning to up, the next 90-degree turn points right." },
  "practice-spa-20": { correctIndex: 2, explanation: "Each shape adds one side: three, four, five, then six sides. A six-sided shape is a hexagon." },
  "practice-spa-21": { correctIndex: 3, explanation: "The third cell combines the quantities in the first two cells. Four plus two gives six squares." },
  "practice-spa-22": { correctIndex: 3, explanation: "The problem explicitly pairs opposite faces B and E, so E is opposite B." },
  "practice-spa-23": { correctIndex: 2, explanation: "Opposite faces cannot share an edge. Because green is opposite yellow, those two colors cannot touch." },
  "practice-spa-24": { correctIndex: 1, explanation: "The north and south movements cancel. Three blocks east followed by one west leaves two blocks east." },
  "practice-spa-25": { correctIndex: 0, explanation: "Horizontal movement ends three units west, and vertical movement ends four units south of the starting point." },
};
