import type { AnswerKey } from "./diagnostic";
import { rotatedCorrectIndex } from "./question-choice-rotation";

const logicAnswers: Array<[number, string]> = [
  [1, "Because every Vim is a Rek and no Rek is a Sot, no Vim can be a Sot."],
  [1, "The Daks that are Mors must also be Tefs because every Mor is a Tef."],
  [1, "Every Jat is a Pel, and no Pel is a Nor, so no Jat can be a Nor."],
  [2, "The first statement directly guarantees that every Wex is a Zim; no other option must follow."],
  [1, "The Bors that are Cets cannot be Luns, so at least some Bors are not Luns."],
  [1, "The required order is Lena, Amir, Bo, Cara, placing Amir second."],
  [0, "J is taller than K, while M and N are both below K, so J must be tallest."],
  [2, "The forced stack is P above Q above R, while S is above P, making R lowest."],
  [1, "Wes must precede Uma, who precedes Tara, who precedes Vic."],
  [3, "The constraints force A, B, D, C, E, so D occupies the third position."],
  [1, "The contrapositive applies: if no alerts were sent, the server was not offline."],
  [2, "A red label can have causes other than fragility, so the package may or may not be fragile."],
  [2, "N implies P, and P implies R. Selecting N therefore requires both P and R."],
  [1, "Approval requires payment. Because payment did not occur, approval could not occur."],
  [2, "If either A or B would force C, the absence of C means neither A nor B attended."],
  [0, "Moving M, I, N, and T forward one letter produces N, J, O, and U."],
  [0, "Reversing the letters of GRAIN produces NIARG."],
  [0, "Odd positions move forward and even positions move back: COLD becomes DNMC."],
  [0, "Alphabet opposites map D to W, O to L, and G to T, producing WLT."],
  [0, "Reversing MATH gives HTAM; moving each letter forward gives IUBN."],
  [3, "Sixteen, 25, 36, and 49 are perfect squares. Forty-five is not."],
  [3, "The first, second, third, and fifth pairs cube the first number. Five cubed is 125, not 100."],
  [4, "The first four strings read the same forward and backward. IJJK does not."],
  [4, "Twenty-two, 33, 44, and 55 repeat one digit and are multiples of 11; 65 does not fit."],
  [3, "The intended rule is one less than consecutive squares: 3, 8, 15, 24, 35, 48. Thus 34 breaks it."],
  [2, "The jumps grow by one: plus 3, 4, 5, 6, then 7. V plus 7 wraps to C."],
  [2, "Starting letters advance by 2, 3, 4, then 5, giving O; the pair is OP."],
  [0, "The backward jumps are 3, 4, 5, 6, then 7 letters, taking H to A."],
  [2, "First letters move forward by 2, 3, 4, 5 to O; second letters move back by 2, 3, 4, 5 to L."],
  [1, "Odd-position letters are B, D, F, H while even-position letters are E, H, K, N."],
  [2, "Letter jumps increase from 2 through 5, giving O, while the numbers double to 16."],
  [2, "Letters move backward by 3, 4, 5, then 6 to H, while numbers double to 32."],
  [2, "Letter jumps grow from 3 through 6 to T, and the numbers double to 48."],
  [2, "The numbers follow n(n+1), giving 30, and letter positions follow triangular numbers, giving O."],
  [3, "Odd-position letters rise C, E, G while even-position letters rise F, H, J; the number doubles to 32."],
  [2, "Two days after Monday is Wednesday."],
  [2, "The only weekday after Tuesday and before Thursday is Wednesday."],
  [1, "Counting back three days from Saturday gives Wednesday."],
  [3, "After excluding Tuesday and Wednesday, Thursday is the only day after Monday and before Friday."],
  [1, "A Friday review places the meeting Wednesday and training one day earlier on Tuesday."],
  [0, "If A is false and exactly one statement is true, B must be selected."],
  [0, "If M is truthful, N's claim that both are truthful is false, satisfying the exactly-one condition."],
  [0, "Every label is wrong, so the Mixed-labeled box is not mixed. Drawing red identifies it as red-only."],
  [3, "Testing the statements shows exactly one is true when either A or C did it, but the evidence cannot distinguish those two."],
  [2, "Only Q being truthful makes its claim correct, so R is marked; P and R then make false claims."],
  [0, "A striped square is striped and noncircular, satisfying both parts of the rule."],
  [0, "A7-42 starts with a letter, contains one hyphen, and ends in an even digit."],
  [2, "Twenty-seven is greater than 20, divisible by 3, and not divisible by 2."],
  [2, "CLOUD has five letters and begins with C while ending with the consecutive letter D."],
  [0, "Two and five differ by 3, have an even product, and sum to 7, which is divisible by 7."],
];

const spatialAnswers: Array<[number, string]> = [
  [1, "A 90-degree clockwise turn from north points east."],
  [3, "A 180-degree turn from east points west."],
  [2, "Turning southwest 90 degrees counterclockwise points southeast."],
  [1, "South plus 135 degrees clockwise reaches northwest; 45 degrees back ends west."],
  [2, "Northwest rotated 225 degrees clockwise ends at south."],
  [0, "East turned 270 degrees counterclockwise points south; another 180 degrees points north."],
  [2, "Northeast minus 135 degrees reaches west, then 270 degrees clockwise reaches south."],
  [2, "Three 45-degree clockwise turns take south to northwest; 90 degrees back gives southwest."],
  [4, "Two 135-degree clockwise turns total 270 degrees, taking west to south."],
  [3, "A 315-degree counterclockwise turn equals 45 clockwise, reaching south; another 90 clockwise reaches west."],
  [1, "A vertical mirror reverses the left-to-right order, producing C-B-A."],
  [0, "A horizontal mirror reverses vertical direction, so down becomes up."],
  [1, "A vertical reflection changes northeast to northwest."],
  [1, "The vertical mirror reverses order and flips horizontal direction, producing up, circle, right."],
  [1, "Vertical reflection changes southeast to southwest; horizontal reflection then changes it to northwest."],
  [0, "The arrow rotates 90 degrees clockwise through up, right, down, left, then up."],
  [3, "The sequence adds one side each time, so a seven-sided figure follows."],
  [2, "Moving clockwise around the square after bottom-right reaches bottom-left."],
  [1, "After alternating 45- and 90-degree turns, the next 90-degree turn takes south to west."],
  [1, "The direction rotates to left while the dot count increases from three to four."],
  [2, "The third cell totals the first two quantities, so one plus four gives five squares."],
  [0, "Applying the same 90-degree turn that changes up to right changes left to up."],
  [2, "The third cell combines the outline and filled versions, producing both squares."],
  [3, "Each row increases side count by one, so the bottom row ends with a hexagon."],
  [2, "The opposite of a right-pointing direction is left."],
  [4, "The stated opposite pair for C is F."],
  [1, "Opposite cube faces cannot share an edge; green is opposite red."],
  [2, "Rolling toward the front brings the former back face E to the top."],
  [4, "The face opposite right-side C lies on the left; C is opposite F."],
  [3, "The corner opposite the A-B-C corner is formed by their respective opposites D-E-F."],
  [4, "With red on top and green in front, a side face may be white or black; white is the listed possibility."],
  [3, "Rolling right brings the former left face onto the top."],
  [1, "Two forward rolls turn the cube 180 degrees, bringing the original bottom to the top."],
  [4, "Rolling right brings the left face up; rolling toward the front then brings the original back face to the top."],
  [4, "Top-bottom are 1-6 and front-back are 2-5, leaving 3 or 4 for the right; 3 is listed."],
  [0, "The final displacement is two blocks east and three blocks north."],
  [0, "The east and west legs cancel, leaving five blocks north."],
  [0, "Net movement is four west and two north."],
  [0, "The route moves three east and four north from the start."],
  [0, "Moving west four, south three, then east one ends three west and three south."],
  [0, "The southeast leg cancels four north units and adds four east; the final south leg cancels the remaining north."],
  [0, "The drone ends three units west and four units south after the east and west legs combine."],
  [0, "Combining all legs gives four west and five north."],
  [0, "The successive turns produce a final displacement of five west and two south."],
  [0, "Combining diagonal and straight components leaves one east and two north."],
  [1, "One fold creates two layers, so a punch away from the fold produces two holes."],
  [2, "Two perpendicular folds create four layers, producing four symmetric holes."],
  [3, "Three folds normally create eight layers, so one punch produces eight holes."],
  [2, "Unfolding across two center folds reflects the punch into four symmetric positions."],
  [1, "A punch on one fold does not duplicate across that fold, but it duplicates across the other, producing two holes."],
];

export const LOGIC_SPATIAL_EXPANSION_ANSWER_KEY: AnswerKey = {
  ...keys("practice-log-", 27, logicAnswers),
  ...keys("practice-spa-", 26, spatialAnswers),
};

function keys(prefix: string, start: number, answers: Array<[number, string]>) {
  return Object.fromEntries(answers.map(([correctIndex, explanation], offset) => {
    const id = `${prefix}${start + offset}`;
    return [id, { correctIndex: rotatedCorrectIndex(id, correctIndex), explanation }];
  }));
}
