import type { PracticeQuestion } from "./practice";
import { rotateQuestionChoices } from "./question-choice-rotation";

const logic: PracticeQuestion[] = [
  q("practice-log-27", "All Vims are Reks. No Rek is a Sot. Which statement must be true?", ["Some Vims are Sots", "No Vims are Sots", "Every Sot is a Vim", "Some Reks are Sots", "No Vims exist"], 2, "syllogisms", 25),
  q("practice-log-28", "Some Daks are Mors. Every Mor is a Tef. Which conclusion is guaranteed?", ["Every Dak is a Tef", "Some Daks are Tefs", "No Dak is a Tef", "Every Tef is a Mor", "Some Mors are not Tefs"], 3, "syllogisms", 30),
  q("practice-log-29", "No Pels are Nors. Every Jat is a Pel. Which statement must be true?", ["Some Jats are Nors", "No Jats are Nors", "Every Nor is a Jat", "No Pels are Jats", "Some Nors are Pels"], 3, "syllogisms", 30),
  q("practice-log-30", "Every Wex is a Zim. Some Zims are Kavs. What can be concluded with certainty?", ["Some Wexes are Kavs", "No Wex is a Kav", "Every Wex is a Zim", "Every Kav is a Wex", "No Zim is a Kav"], 4, "syllogisms", 32),
  q("practice-log-31", "Some Bors are Cets. No Cet is a Lun. Which conclusion must follow?", ["No Bor is a Lun", "Some Bors are not Luns", "Every Bor is a Cet", "Some Luns are Bors", "No Bor is a Cet"], 4, "syllogisms", 34),
  q("practice-log-32", "Lena arrives before Amir, Amir before Bo, and Cara after Bo. Who arrives second?", ["Lena", "Amir", "Bo", "Cara", "Cannot be determined"], 2, "ordering logic", 24),
  q("practice-log-33", "J is taller than K. M is shorter than K but taller than N. Who must be tallest?", ["J", "K", "M", "N", "Cannot be determined"], 2, "ordering logic", 25),
  q("practice-log-34", "Files P, Q, R, and S are stacked. P is above Q, R is below Q, and S is above P. Which file is lowest?", ["P", "Q", "R", "S", "Cannot be determined"], 3, "ordering logic", 28),
  q("practice-log-35", "Tara finishes after Uma but before Vic. Wes finishes before Uma. Which order is required?", ["Uma, Wes, Tara, Vic", "Wes, Uma, Tara, Vic", "Wes, Tara, Uma, Vic", "Uma, Tara, Wes, Vic", "Vic, Tara, Uma, Wes"], 4, "ordering logic", 34),
  q("practice-log-36", "Five tasks A-E are ordered. B follows A, D precedes C, and E follows C. If B precedes D, which task must be third?", ["A", "B", "C", "D", "E"], 5, "ordering logic", 40),
  q("practice-log-37", "If the server is offline, alerts are sent. No alerts were sent. What follows?", ["The server was offline", "The server was not offline", "Alerts failed", "The server restarted", "Nothing follows"], 2, "deductive reasoning", 22),
  q("practice-log-38", "If a package is fragile, it receives a red label. This package has a red label. What is valid?", ["It must be fragile", "It cannot be fragile", "It may or may not be fragile", "Every package is fragile", "The label is wrong"], 3, "deductive reasoning", 25),
  q("practice-log-39", "If N is selected, P is selected. If P is selected, R is selected. N is selected. What must follow?", ["Only P is selected", "Only R is selected", "P and R are selected", "R is not selected", "Nothing follows"], 3, "deductive reasoning", 28),
  q("practice-log-40", "A permit is approved only if the fee is paid. The fee was not paid. What follows?", ["The permit was approved", "The permit was not approved", "The fee was waived", "The permit may be approved", "Nothing follows"], 4, "deductive reasoning", 30),
  q("practice-log-41", "If either A or B attends, C attends. C did not attend. Which statement must be true?", ["A attended", "B attended", "Neither A nor B attended", "Exactly one attended", "Both attended"], 5, "deductive reasoning", 34),
  q("practice-log-42", "A code moves each letter one place forward. How is MINT written?", ["NJOU", "NIOU", "MHOU", "OJPU", "NKPV"], 1, "coding rules", 20),
  q("practice-log-43", "A code reverses each word. How is GRAIN written?", ["NIARG", "NIRAG", "IARNG", "GNIAR", "NAIRG"], 1, "coding rules", 20),
  q("practice-log-44", "In a code, letters in odd positions move forward one and letters in even positions move back one. How is COLD coded?", ["DNMC", "DNKC", "DPMC", "BNMC", "DOMC"], 3, "coding rules", 30),
  q("practice-log-45", "A code replaces each letter with its alphabet opposite: A-Z, B-Y, and so on. How is DOG coded?", ["WLT", "WOG", "ELT", "XMT", "VKS"], 4, "coding rules", 34),
  q("practice-log-46", "A code reverses the word, then moves every letter forward one. How is MATH coded?", ["IUBN", "IUBM", "HTAM", "JVCN", "NBUJ"], 5, "coding rules", 38),
  q("practice-log-47", "Which number does not belong?", ["16", "25", "36", "45", "49"], 2, "classification logic", 20),
  q("practice-log-48", "Which pair follows a different relationship?", ["2:8", "3:27", "4:64", "5:100", "6:216"], 3, "classification logic", 26),
  q("practice-log-49", "Which item differs from the other four?", ["ABBA", "CDDC", "EFFE", "GHHG", "IJJK"], 3, "classification logic", 25),
  q("practice-log-50", "Which number is unlike the others?", ["22", "33", "44", "55", "65"], 2, "classification logic", 20),
  q("practice-log-51", "Which term breaks the rule? 3, 8, 15, 24, 34, 48", ["8", "15", "24", "34", "48"], 5, "classification logic", 36),
  q("practice-log-52", "Which letter comes next? D, G, K, P, V, ?", ["A", "B", "C", "D", "E"], 4, "letter series", 30),
  q("practice-log-53", "Which pair comes next? AB, CD, FG, JK, ?", ["MN", "NO", "OP", "PQ", "QR"], 4, "letter series", 32),
  q("practice-log-54", "Which letter comes next? Z, W, S, N, H, ?", ["A", "B", "C", "D", "E"], 5, "letter series", 34),
  q("practice-log-55", "Which pair comes next? AZ, CX, FU, JQ, ?", ["NL", "NM", "OL", "OM", "PL"], 5, "letter series", 38),
  q("practice-log-56", "Which letter completes the pattern? B, E, D, H, F, K, H, ?", ["M", "N", "O", "P", "Q"], 4, "letter series", 34),
  q("practice-log-57", "What comes next? A1, C2, F4, J8, ?", ["N16", "O12", "O16", "P16", "P20"], 4, "mixed series", 34),
  q("practice-log-58", "What comes next? Z2, W4, S8, N16, ?", ["G24", "H24", "H32", "I32", "J36"], 5, "mixed series", 38),
  q("practice-log-59", "What comes next? B3, E6, I12, N24, ?", ["S36", "T36", "T48", "U48", "V52"], 5, "mixed series", 38),
  q("practice-log-60", "What comes next? 2A, 6C, 12F, 20J, ?", ["28N", "30N", "30O", "32O", "32P"], 5, "mixed series", 40),
  q("practice-log-61", "What comes next? C1, F2, E4, H8, G16, ?", ["I24", "I32", "J24", "J32", "K32"], 4, "mixed series", 36),
  q("practice-log-62", "A workshop is two days after Monday. On which day is it?", ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"], 1, "scheduling logic", 16),
  q("practice-log-63", "A review occurs before Thursday but after Tuesday. On which day is it?", ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"], 1, "scheduling logic", 16),
  q("practice-log-64", "Training is three days before Saturday. On which day is training?", ["Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"], 2, "scheduling logic", 18),
  q("practice-log-65", "The audit is after Monday, before Friday, and is neither Tuesday nor Wednesday. Which day is it?", ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"], 4, "scheduling logic", 28),
  q("practice-log-66", "A meeting is one day after training and two days before the review. If review is Friday, when is training?", ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"], 4, "scheduling logic", 30),
  q("practice-log-67", "Exactly one statement is true: (1) A is selected. (2) B is selected. If A is not selected, what follows?", ["B is selected", "B is not selected", "Both are selected", "Neither is selected", "Cannot be known"], 3, "truth logic", 28),
  q("practice-log-68", "M says, 'N is lying.' N says, 'Both of us are truthful.' If exactly one is truthful, who is truthful?", ["M only", "N only", "Both", "Neither", "Cannot be known"], 4, "truth logic", 34),
  q("practice-log-69", "Three boxes are labeled Red, Blue, and Mixed, but every label is wrong. A red ball is drawn from the box labeled Mixed. What is that box?", ["Red only", "Blue only", "Actually mixed", "Empty", "Cannot be known"], 5, "truth logic", 40),
  q("practice-log-70", "A says B did it. B says C did it. C says B is lying. Exactly one statement is true. Who did it?", ["A", "B", "C", "A or C", "Cannot be determined"], 5, "truth logic", 42),
  q("practice-log-71", "One of four cards is marked. P says 'Q is marked.' Q says 'R is marked.' R says 'R is not marked.' If only Q tells the truth, which card is marked?", ["P", "Q", "R", "S", "Cannot be determined"], 5, "truth logic", 44),
  q("practice-log-72", "Rule: select a figure only if it is striped and not circular. Which qualifies?", ["Striped square", "Striped circle", "Plain square", "Plain triangle", "Circular grid"], 1, "rule application", 18),
  q("practice-log-73", "Rule: a code is valid when it starts with a letter, ends with an even digit, and contains exactly one hyphen. Which is valid?", ["A7-42", "B-315", "C24--8", "D2-63", "E28"], 3, "rule application", 28),
  q("practice-log-74", "Rule: admit values greater than 20 that are divisible by 3 but not by 2. Which value is admitted?", ["18", "24", "27", "30", "36"], 3, "rule application", 24),
  q("practice-log-75", "Rule: accept a word if its first and last letters are consecutive alphabetically and it has five letters. Which is accepted?", ["ALERT", "BRICK", "CLOUD", "DREAM", "EAGLE"], 4, "rule application", 34),
  q("practice-log-76", "Rule: choose a pair whose sum is divisible by 7, product is even, and larger number exceeds the smaller by 3. Which qualifies?", ["2 and 5", "3 and 6", "4 and 7", "5 and 8", "6 and 9"], 5, "rule application", 38),
];

const spatial: PracticeQuestion[] = [
  q("practice-spa-26", "A pointer faces north and turns 90 degrees clockwise. Which direction does it face?", ["North", "East", "South", "West", "Northeast"], 1, "mental rotation", 16),
  q("practice-spa-27", "A pointer faces east and turns 180 degrees. Which direction does it face?", ["North", "East", "South", "West", "Southeast"], 1, "mental rotation", 16),
  q("practice-spa-28", "A marker faces southwest and turns 90 degrees counterclockwise. Which direction does it face?", ["Northwest", "Northeast", "Southeast", "South", "West"], 2, "mental rotation", 20),
  q("practice-spa-29", "An arrow faces south, turns 135 degrees clockwise, then 45 degrees counterclockwise. Where does it point?", ["East", "West", "North", "Southeast", "Southwest"], 3, "mental rotation", 26),
  q("practice-spa-30", "A pointer faces northwest and turns 225 degrees clockwise. Where does it point?", ["North", "East", "South", "West", "Southeast"], 4, "mental rotation", 30),
  q("practice-spa-31", "A marker faces east, turns 270 degrees counterclockwise, then 180 degrees clockwise. Where does it face?", ["North", "East", "South", "West", "Northeast"], 4, "mental rotation", 32),
  q("practice-spa-32", "A pointer faces northeast, turns 135 degrees counterclockwise, then 270 degrees clockwise. Where does it face?", ["North", "East", "South", "West", "Southwest"], 5, "mental rotation", 36),
  q("practice-spa-33", "A robot points south, turns 45 degrees clockwise three times, then 90 degrees counterclockwise. Where does it point?", ["East", "West", "Southwest", "Southeast", "Northwest"], 5, "mental rotation", 38),
  q("practice-spa-34", "A pointer faces west. It turns 135 degrees clockwise twice. Which direction does it face?", ["North", "Northeast", "East", "Southeast", "South"], 4, "mental rotation", 32),
  q("practice-spa-35", "An arrow faces southeast, rotates 315 degrees counterclockwise, then 90 degrees clockwise. Where does it point?", ["North", "Northeast", "East", "West", "Southwest"], 5, "mental rotation", 38),
  q("practice-spa-36", "A vertical mirror reverses the arrangement A-B-C. What order appears?", ["A-B-C", "C-B-A", "B-C-A", "C-A-B", "B-A-C"], 1, "reflection", 16),
  q("practice-spa-37", "A horizontal mirror is placed below a downward arrow. Which way does the reflection point?", ["Up", "Down", "Left", "Right", "Northeast"], 1, "reflection", 16),
  q("practice-spa-38", "A vertical mirror is placed to the right of a northeast arrow. Which direction appears?", ["Northeast", "Northwest", "Southeast", "Southwest", "North"], 2, "reflection", 20),
  q("practice-spa-39", "The arrangement left-arrow, circle, up-arrow is reflected in a vertical mirror. Which order and directions appear?", ["right-arrow, circle, up-arrow", "up-arrow, circle, right-arrow", "up-arrow, circle, left-arrow", "left-arrow, circle, up-arrow", "down-arrow, circle, right-arrow"], 4, "reflection", 32),
  q("practice-spa-40", "A southeast arrow is reflected first in a vertical mirror and then in a horizontal mirror. Which direction results?", ["Northeast", "Northwest", "Southeast", "Southwest", "South"], 4, "reflection", 30),
  q("practice-spa-41", "What comes next in the rotation sequence? Up, right, down, left, ?", ["Up", "Right", "Down", "Left", "Northeast"], 1, "visual sequences", 16),
  q("practice-spa-42", "A shape sequence has 3 sides, 4 sides, 5 sides, then 6 sides. How many sides are next?", ["4", "5", "6", "7", "8"], 1, "visual sequences", 16),
  q("practice-spa-43", "A dot moves around square corners clockwise: top-left, top-right, bottom-right, ?. Where next?", ["Top-left", "Top-right", "Bottom-left", "Bottom-right", "Center"], 2, "visual sequences", 20),
  q("practice-spa-44", "An arrow sequence rotates clockwise by 45, then 90, then 45 degrees, repeating. Starting north: north, northeast, southeast, south, ?", ["Southwest", "West", "Northwest", "East", "North"], 4, "visual sequences", 32),
  q("practice-spa-45", "A sequence alternates adding one dot and rotating 90 degrees: up with 1 dot, right with 2, down with 3, ?. What follows?", ["Left with 3", "Left with 4", "Up with 4", "Right with 4", "Down with 5"], 4, "visual sequences", 34),
  q("practice-spa-46", "Matrix rule: the third cell contains the total symbols from the first two. Top: 2 circles, 3 circles, 5 circles. Bottom: 1 square, 4 squares, ?", ["3 squares", "4 squares", "5 squares", "6 squares", "7 squares"], 2, "figure matrices", 22),
  q("practice-spa-47", "Matrix rule: the third arrow is the first arrow rotated toward the second by 90 degrees. Top: up, right, right. Bottom: left, up, ?", ["Up", "Right", "Down", "Left", "Northeast"], 3, "figure matrices", 28),
  q("practice-spa-48", "Matrix rule: filled and outline symbols combine in the third cell. Top: outline circle, filled circle, both circles. Bottom: outline square, filled square, ?", ["Outline square", "Filled square", "Both squares", "Two circles", "Empty cell"], 3, "figure matrices", 28),
  q("practice-spa-49", "Matrix rule: each row increases sides by one. Top: triangle, square, pentagon. Bottom: square, pentagon, ?", ["Triangle", "Square", "Pentagon", "Hexagon", "Heptagon"], 3, "figure matrices", 26),
  q("practice-spa-50", "Matrix rule: third direction is the opposite of the combination of the first two identical directions. Top: up, up, down. Bottom: right, right, ?", ["Up", "Down", "Left", "Right", "Northeast"], 4, "figure matrices", 32),
  q("practice-spa-51", "A cube has opposite pairs A-D, B-E, and C-F. Which face is opposite C?", ["A", "B", "D", "E", "F"], 1, "cube relations", 16),
  q("practice-spa-52", "On a cube, red is opposite green. Which color cannot share an edge with red?", ["Blue", "Green", "White", "Yellow", "Black"], 1, "cube relations", 16),
  q("practice-spa-53", "A cube has top A, front B, right C, and B opposite E. It rolls toward its front face once. Which face becomes the top?", ["A", "B", "E", "C", "Cannot be known"], 3, "cube relations", 28),
  q("practice-spa-54", "A cube has top A, front B, right C, and opposite pairs A-D, B-E, C-F. Which face is on the left?", ["A", "B", "D", "E", "F"], 2, "cube relations", 22),
  q("practice-spa-55", "A cube shows A on top, B in front, and C on the right. Which three faces meet at the opposite corner?", ["A, B, C", "A, E, F", "D, B, F", "D, E, F", "D, E, C"], 4, "cube relations", 34),
  q("practice-spa-56", "A cube has opposite colors red-blue, green-yellow, white-black. If red is on top and green is in front, which color could be on the right?", ["Red", "Blue", "Green", "Yellow", "White"], 4, "cube relations", 34),
  q("practice-spa-57", "A cube with top A, front B, right C rolls right once. Which face becomes top?", ["A", "B", "C", "The former left face", "Cannot be known"], 3, "cube relations", 28),
  q("practice-spa-58", "A cube rolls forward twice. Relative to its starting position, which face is now on top?", ["Original top", "Original bottom", "Original front", "Original back", "Original right"], 3, "cube relations", 28),
  q("practice-spa-59", "A cube starts with A top, B front, C right. It rolls right, then toward its front. Which original face is now on top?", ["A", "B", "C", "The original bottom", "The original back"], 5, "cube relations", 40),
  q("practice-spa-60", "Opposite cube faces total 7: 1-6, 2-5, 3-4. If 1 is top and 2 is front, which number could be on the right?", ["1", "2", "5", "6", "3"], 4, "cube relations", 34),
  q("practice-spa-61", "A person walks 3 blocks north and 2 east. Where are they relative to the start?", ["2 east and 3 north", "3 east and 2 north", "2 west and 3 north", "3 south and 2 east", "At the start"], 1, "spatial tracking", 18),
  q("practice-spa-62", "A person walks 5 east, 5 north, then 5 west. Where are they?", ["5 north", "5 south", "5 east", "5 west", "At the start"], 1, "spatial tracking", 18),
  q("practice-spa-63", "A robot moves 4 north, 7 west, 2 south, and 3 east. Where is it relative to start?", ["4 west and 2 north", "2 west and 4 north", "4 east and 2 north", "4 west and 2 south", "At the start"], 2, "spatial tracking", 24),
  q("practice-spa-64", "Facing north, Mira turns right, walks 3, turns left, walks 4. Where is she relative to start?", ["3 east and 4 north", "4 east and 3 north", "3 west and 4 north", "3 east and 4 south", "At the start"], 2, "spatial tracking", 24),
  q("practice-spa-65", "Facing west, a robot moves 4, turns left and moves 3, then turns left and moves 1. Where is it?", ["3 west and 3 south", "3 west and 3 north", "5 west and 3 south", "3 east and 3 south", "At the start"], 3, "spatial tracking", 28),
  q("practice-spa-66", "A hiker walks 6 north, 4 southeast diagonally, then 2 south. Treat each diagonal step as one east and one south. Where is the hiker?", ["4 east", "4 east and 2 north", "4 east and 2 south", "2 east and 4 north", "At the start"], 4, "spatial tracking", 32),
  q("practice-spa-67", "Starting east, a drone flies 5, turns 90 degrees clockwise for 4, then 90 clockwise for 8. Where is it?", ["3 west and 4 south", "3 east and 4 south", "3 west and 4 north", "13 east and 4 south", "At the start"], 3, "spatial tracking", 30),
  q("practice-spa-68", "A courier travels 8 north, 3 east, 5 south, 7 west, and 2 north. Where is the courier?", ["4 west and 5 north", "5 west and 4 north", "4 east and 5 north", "4 west and 1 north", "At the start"], 4, "spatial tracking", 34),
  q("practice-spa-69", "Facing south, a robot moves 6, turns right for 2, turns right for 4, then left for 3. Where is it?", ["5 west and 2 south", "5 east and 2 south", "1 west and 2 south", "5 west and 2 north", "At the start"], 5, "spatial tracking", 38),
  q("practice-spa-70", "A walker moves 5 northeast, 3 west, 2 south, and 1 southwest. Treat diagonals as equal horizontal and vertical units. Where are they?", ["1 east and 2 north", "2 east and 1 north", "1 west and 2 north", "2 east and 1 south", "At the start"], 5, "spatial tracking", 40),
  q("practice-spa-71", "A square sheet is folded in half once. One hole is punched through the folded sheet. How many holes appear when unfolded?", ["1", "2", "3", "4", "8"], 1, "paper folding", 18),
  q("practice-spa-72", "A square sheet is folded in half twice along perpendicular center lines. One hole is punched away from the folds. How many holes appear when unfolded?", ["2", "3", "4", "6", "8"], 2, "paper folding", 22),
  q("practice-spa-73", "A sheet is folded in half three times. A single hole is punched through all layers. How many holes normally appear when fully unfolded?", ["3", "4", "6", "8", "12"], 3, "paper folding", 26),
  q("practice-spa-74", "A square is folded left-to-right, then bottom-to-top. A hole is punched at the folded square's top-right corner, away from fold edges. Where do holes appear when unfolded?", ["One corner", "Two top corners", "All four symmetric positions", "Only the center", "Along one edge"], 4, "paper folding", 34),
  q("practice-spa-75", "A sheet is folded in half twice. A punch lies exactly on one fold edge but away from the other. How many distinct holes appear when unfolded?", ["1", "2", "3", "4", "8"], 5, "paper folding", 38),
];

export const LOGIC_SPATIAL_EXPANSION_QUESTIONS = [...logic, ...spatial].map(rotateQuestionChoices);

function q(id: string, prompt: string, choices: string[], difficulty: 1 | 2 | 3 | 4 | 5, skill: string, targetSeconds: number): PracticeQuestion {
  return { id, category: id.includes("-log-") ? "Logic" : "Spatial", prompt, choices, difficulty, skill, targetSeconds };
}
