import type { PracticeQuestion } from "./practice";

export const BALANCED_EXPANSION_QUESTIONS: PracticeQuestion[] = [
  { id: "practice-balanced-ver-01", category: "Verbal", prompt: "AUSTERE most nearly means:", choices: ["Ornate", "Severe", "Cheerful", "Flexible", "Temporary"], targetSeconds: 23, difficulty: 4, skill: "vocabulary" },
  { id: "practice-balanced-ver-02", category: "Verbal", prompt: "PLACATE most nearly means:", choices: ["Provoke", "Observe", "Calm", "Replace", "Question"], targetSeconds: 22, difficulty: 3, skill: "vocabulary" },
  { id: "practice-balanced-ver-03", category: "Verbal", prompt: "PERFUNCTORY most nearly means:", choices: ["Thorough", "Routine and careless", "Unusually generous", "Secretive", "Highly technical"], targetSeconds: 25, difficulty: 5, skill: "vocabulary" },
  { id: "practice-balanced-ver-04", category: "Verbal", prompt: "COMPASS is to DIRECTION as THERMOMETER is to:", choices: ["Weather", "Mercury", "Temperature", "Pressure", "Distance"], targetSeconds: 20, difficulty: 2, skill: "verbal analogies" },
  { id: "practice-balanced-ver-05", category: "Verbal", prompt: "Choose the word most nearly opposite in meaning to TRANSIENT.", choices: ["Brief", "Mobile", "Permanent", "Uncertain", "Visible"], targetSeconds: 21, difficulty: 3, skill: "antonyms" },

  { id: "practice-balanced-num-01", category: "Numerical", prompt: "By what percentage did output increase from January to April?", choices: ["60%", "70%", "75%", "80%", "90%"], targetSeconds: 32, difficulty: 3, skill: "data interpretation", stimulus: { kind: "bar", title: "Monthly output", labels: ["Jan", "Feb", "Mar", "Apr"], values: [80, 96, 120, 144], unit: "units" } },
  { id: "practice-balanced-num-02", category: "Numerical", prompt: "Which team had the highest hiring rate?", choices: ["Alpha", "Beta", "Gamma", "Delta", "Alpha and Delta"], targetSeconds: 34, difficulty: 4, skill: "data interpretation", stimulus: { kind: "table", title: "Hiring by team", columns: ["Applicants", "Hired"], rows: [{ label: "Alpha", values: [60, 12] }, { label: "Beta", values: [80, 20] }, { label: "Gamma", values: [100, 30] }, { label: "Delta", values: [120, 24] }] } },
  { id: "practice-balanced-num-03", category: "Numerical", prompt: "How many fewer defects were recorded on Friday than on Monday?", choices: ["8", "10", "11", "13", "15"], targetSeconds: 24, difficulty: 2, skill: "data interpretation", stimulus: { kind: "line", title: "Daily defects", labels: ["Mon", "Tue", "Wed", "Thu", "Fri"], values: [18, 15, 12, 10, 5], unit: "defects" } },
  { id: "practice-balanced-num-04", category: "Numerical", prompt: "What is 5³ ÷ 5?", choices: ["5", "15", "25", "50", "125"], targetSeconds: 22, difficulty: 3, skill: "exponents" },
  { id: "practice-balanced-num-05", category: "Numerical", prompt: "Using π = 22/7, what is the circumference of a circle with diameter 14?", choices: ["22", "28", "44", "88", "154"], targetSeconds: 28, difficulty: 3, skill: "geometry" },
  { id: "practice-balanced-num-06", category: "Numerical", prompt: "If 3x + y = 17 and x + y = 9, what is x?", choices: ["3", "4", "5", "6", "8"], targetSeconds: 32, difficulty: 4, skill: "systems of equations" },
  { id: "practice-balanced-num-07", category: "Numerical", prompt: "4 is to 18 as 7 is to what number?", choices: ["42", "47", "49", "51", "56"], targetSeconds: 28, difficulty: 4, skill: "numerical analogies" },
  { id: "practice-balanced-num-08", category: "Numerical", prompt: "If x is positive and x² - 5x = 24, what is x?", choices: ["3", "5", "6", "8", "12"], targetSeconds: 38, difficulty: 5, skill: "quadratic reasoning" },

  { id: "practice-balanced-log-01", category: "Logic", prompt: "In a code, each consonant moves forward one letter and each vowel stays unchanged. How is MATE coded?", choices: ["NBUF", "NBUE", "NATE", "MBUF", "NAUE"], targetSeconds: 30, difficulty: 3, skill: "coding rules" },
  { id: "practice-balanced-log-02", category: "Logic", prompt: "A code reverses the letters, then moves the new first letter forward one. How is TONE coded?", choices: ["FNOT", "ENOU", "FNOU", "EOOT", "FNOE"], targetSeconds: 34, difficulty: 4, skill: "coding rules" },
  { id: "practice-balanced-log-03", category: "Logic", prompt: "What comes next? A2, C4, F8, J16, ?", choices: ["N24", "N32", "O24", "O32", "P32"], targetSeconds: 34, difficulty: 4, skill: "mixed series" },
  { id: "practice-balanced-log-04", category: "Logic", prompt: "What comes next? Z1, W2, S4, N8, ?", choices: ["G16", "H12", "H16", "I16", "J10"], targetSeconds: 36, difficulty: 5, skill: "mixed series" },
  { id: "practice-balanced-log-05", category: "Logic", prompt: "Which item does not belong?", choices: ["ABBA", "CDDC", "EFFE", "GHHG", "IJJK"], targetSeconds: 24, difficulty: 3, skill: "classification logic" },
  { id: "practice-balanced-log-06", category: "Logic", prompt: "Rule: a valid tag has exactly two letters followed by three digits, and its final digit is odd. Which tag is valid?", choices: ["AB-123", "A1234", "CD248", "EF731", "GH92X"], targetSeconds: 27, difficulty: 3, skill: "rule application" },

  { id: "practice-balanced-spa-01", category: "Spatial", prompt: "Which option replaces the question mark?", choices: ["●●", "●●●", "■■", "■■■", "○○○"], targetSeconds: 28, difficulty: 3, skill: "figure matrices", stimulus: { kind: "matrix", title: "Complete the missing cell", rows: [["○", "○○", "○○○"], ["●", "●●", "?"]] } },
  { id: "practice-balanced-spa-02", category: "Spatial", prompt: "In each row, the third cell places the first symbol before the second. Which option completes the matrix?", choices: ["■□", "□■", "■○", "□○", "○□"], targetSeconds: 30, difficulty: 4, skill: "figure matrices", stimulus: { kind: "matrix", title: "Complete the missing cell", rows: [["▲", "△", "▲△"], ["■", "□", "?"]] } },
  { id: "practice-balanced-spa-03", category: "Spatial", prompt: "Which symbol continues the sequence? ▲, ▶, ▼, ◀, ▲, ?", choices: ["▲", "▶", "▼", "◀", "◆"], targetSeconds: 20, difficulty: 2, skill: "visual sequences" },
  { id: "practice-balanced-spa-04", category: "Spatial", prompt: "Which group continues the pattern? ○, ○■, ○■■, ○■■■, ?", choices: ["○○○○", "○■■■■", "■■■■○", "○■○■", "■■■■"], targetSeconds: 24, difficulty: 3, skill: "visual sequences" },
  { id: "practice-balanced-spa-05", category: "Spatial", prompt: "A vertical mirror is placed to the right of the sequence ◀ ● ■. What appears in the mirror from left to right?", choices: ["▶ ● ■", "■ ● ▶", "■ ● ◀", "◀ ● ■", "● ■ ▶"], targetSeconds: 30, difficulty: 4, skill: "reflection" },
  { id: "practice-balanced-spa-06", category: "Spatial", prompt: "An arrow points southeast. It turns 135° counterclockwise. Which direction does it face?", choices: ["North", "Northeast", "East", "South", "West"], targetSeconds: 28, difficulty: 4, skill: "mental rotation" },
];
