import type { Question } from "./diagnostic";

export const PRACTICE_TEST_SECONDS = 6 * 60;

export const PRACTICE_TEST_QUESTIONS: Question[] = [
  {
    id: "pt-ver-01",
    category: "Verbal",
    prompt: "COMPASS is to DIRECTION as SCALE is to:",
    choices: ["Distance", "Weight", "Height", "Speed", "Volume"],
    difficulty: 1,
    targetSeconds: 18,
    itemFamily: "verbal analogies",
  },
  {
    id: "pt-num-01",
    category: "Numerical",
    prompt: "84 is 35% of what number?",
    choices: ["210", "220", "230", "240", "250"],
    difficulty: 2,
    targetSeconds: 18,
    itemFamily: "percentages",
  },
  {
    id: "pt-spa-01",
    category: "Spatial",
    prompt: "Which symbol continues the sequence? ↑  ↗  →  ↘  ?",
    choices: ["↓", "↙", "←", "↖", "↑"],
    difficulty: 2,
    targetSeconds: 18,
    itemFamily: "mental rotation",
  },
  {
    id: "pt-ver-02",
    category: "Verbal",
    prompt:
      "Although the route was ___, the guide's instructions were so ___ that nobody became lost.",
    choices: [
      "short · vague",
      "complex · precise",
      "familiar · careless",
      "direct · confusing",
      "hidden · incomplete",
    ],
    difficulty: 2,
    targetSeconds: 18,
    itemFamily: "sentence completion",
  },
  {
    id: "pt-num-02",
    category: "Numerical",
    prompt: "Which value is greatest?",
    choices: ["0.805", "0.85", "0.815", "0.058", "0.508"],
    difficulty: 1,
    targetSeconds: 18,
    itemFamily: "fractions and proportions",
  },
  {
    id: "pt-log-01",
    category: "Logic",
    prompt:
      "All Vals are Nors. Some Nors are Peks. Which statement must be true?",
    choices: [
      "All Peks are Vals",
      "Some Vals are Peks",
      "All Vals are Nors",
      "No Nors are Peks",
      "No Vals are Peks",
    ],
    difficulty: 2,
    targetSeconds: 18,
    itemFamily: "syllogisms",
  },
  {
    id: "pt-num-03",
    category: "Numerical",
    prompt: "What number comes next? 52, 47, 41, 34, 26, ?",
    choices: ["15", "16", "17", "18", "19"],
    difficulty: 2,
    targetSeconds: 18,
    itemFamily: "number sequences",
  },
  {
    id: "pt-ver-03",
    category: "Verbal",
    prompt: "Choose the word most nearly opposite to SPARSE.",
    choices: ["Dense", "Remote", "Thin", "Scattered", "Small"],
    difficulty: 2,
    targetSeconds: 18,
    itemFamily: "antonyms",
  },
  {
    id: "pt-spa-02",
    category: "Spatial",
    prompt: "Which figure completes the pattern? ○  ●●  ○○○  ●●●●  ?",
    choices: ["○○○○○", "●●●●●", "○○○○", "●●●", "○●○●○"],
    difficulty: 2,
    targetSeconds: 18,
    itemFamily: "visual sequences",
  },
  {
    id: "pt-num-04",
    category: "Numerical",
    prompt:
      "Four values have an average of 27. Three are 19, 24, and 31. What is the fourth?",
    choices: ["30", "32", "34", "36", "38"],
    difficulty: 2,
    targetSeconds: 18,
    itemFamily: "averages",
  },
  {
    id: "pt-ver-04",
    category: "Verbal",
    prompt: "What group of letters comes next? ADG, BEH, CFI, ?",
    choices: ["DGJ", "DFJ", "EGJ", "DGI", "EHJ"],
    difficulty: 3,
    targetSeconds: 18,
    itemFamily: "letter series",
  },
  {
    id: "pt-num-05",
    category: "Numerical",
    prompt:
      "A rectangle's length is three times its width. Its perimeter is 64. What is its width?",
    choices: ["6", "8", "10", "12", "16"],
    difficulty: 2,
    targetSeconds: 18,
    itemFamily: "basic algebra",
  },
  {
    id: "pt-spa-03",
    category: "Spatial",
    prompt: "Which figure does not belong?",
    choices: ["△○", "▷○", "▽○", "◁○", "△●"],
    difficulty: 2,
    targetSeconds: 18,
    itemFamily: "figure classification",
  },
  {
    id: "pt-ver-05",
    category: "Verbal",
    prompt:
      "How many entries in the left column are exactly the same as the corresponding entry in the right column?",
    choices: ["1", "2", "3", "4", "5"],
    difficulty: 3,
    targetSeconds: 18,
    itemFamily: "attention to detail",
    stimulus: {
      kind: "pairs",
      title: "Compare each row",
      pairs: [
        ["Northstar Analytics", "Northstar Analytics"],
        ["Meridian BioSystems", "Meridian Biosystems"],
        ["Crestview Logistics", "Crestview Logistics"],
        ["Apex River Holdings", "Apex Rvier Holdings"],
        ["Quantum Ridge Labs", "Quantum Ridge Labs"],
      ],
    },
  },
  {
    id: "pt-num-06",
    category: "Numerical",
    prompt:
      "Six identical machines produce 270 parts in 3 hours. How many parts do 4 machines produce in 5 hours?",
    choices: ["240", "270", "300", "320", "360"],
    difficulty: 3,
    targetSeconds: 18,
    itemFamily: "rates and arithmetic",
  },
  {
    id: "pt-log-02",
    category: "Logic",
    prompt:
      "Rhea finishes before Omar. Omar finishes before Luis. Mina finishes after Rhea but before Luis. Who must finish last?",
    choices: ["Rhea", "Omar", "Luis", "Mina", "Cannot tell"],
    difficulty: 2,
    targetSeconds: 18,
    itemFamily: "ordering logic",
  },
  {
    id: "pt-num-07",
    category: "Numerical",
    prompt: "A jacket is reduced by 25% to $72. What was its original price?",
    choices: ["$84", "$90", "$94", "$96", "$108"],
    difficulty: 2,
    targetSeconds: 18,
    itemFamily: "percentages",
  },
  {
    id: "pt-ver-06",
    category: "Verbal",
    prompt: "ARCHIVE is to RECORDS as PANTRY is to:",
    choices: ["Shelves", "Kitchen", "Food", "Door", "Cook"],
    difficulty: 2,
    targetSeconds: 18,
    itemFamily: "verbal analogies",
  },
  {
    id: "pt-spa-04",
    category: "Spatial",
    prompt: "Complete the matrix: top row ○, ○○, ○○○; bottom row ■, ■■, ?",
    choices: ["■", "■■", "■■■", "□□□", "●●●"],
    difficulty: 2,
    targetSeconds: 18,
    itemFamily: "figure matrices",
  },
  {
    id: "pt-num-08",
    category: "Numerical",
    prompt:
      "A phone and charger cost $460 together. The phone costs $400 more than the charger. How much is the phone?",
    choices: ["$400", "$420", "$430", "$440", "$450"],
    difficulty: 3,
    targetSeconds: 18,
    itemFamily: "basic algebra",
  },
];
