export const PRACTICE_ANSWER_KEY: Record<string, { correctIndex: number; explanation: string }> = {
  "practice-num-01": { correctIndex: 2, explanation: "Each machine produces 10 parts per hour. Eight machines working for five hours produce 8 × 5 × 10 = 400 parts." },
  "practice-ver-01": { correctIndex: 1, explanation: "Transparent and opaque are opposites. Flexible and rigid have the same opposite relationship." },
  "practice-log-01": { correctIndex: 2, explanation: "The first statement directly guarantees that every Nib is a Pex. The overlap between Pexes and Jors does not establish anything further about Nibs." },
  "practice-num-02": { correctIndex: 3, explanation: "Each term is the previous term doubled plus 2. Therefore, 78 × 2 + 2 = 158." },
  "practice-spa-01": { correctIndex: 1, explanation: "West turned 270° clockwise points south. Turning 90° counterclockwise from south points east." },
  "practice-ver-02": { correctIndex: 2, explanation: "Concise means brief and economical with words. Verbose means using more words than necessary." },
  "practice-log-02": { correctIndex: 2, explanation: "The order includes Mara before Theo before Jin before Sal, so both Mara and Theo must arrive before Jin." },
  "practice-num-03": { correctIndex: 1, explanation: "The increase is 30. Dividing 30 by the original 120 gives 0.25, or 25%." },
  "practice-ver-03": { correctIndex: 1, explanation: "Although signals a contrast: the evidence was initially inconclusive, but later findings made the conclusion nearly certain." },
  "practice-num-04": { correctIndex: 2, explanation: "Each box holds 4 files, so five identical boxes hold 5 × 4 = 20 files." },
  "practice-num-05": { correctIndex: 2, explanation: "Fifteen percent of $120 is $18. Subtracting $18 from $120 gives a $102 sale price." },
  "practice-num-06": { correctIndex: 2, explanation: "A 20% increase takes $200 to $240. Reducing $240 by 25% subtracts $60, leaving $180." },
  "practice-num-07": { correctIndex: 2, explanation: "The sequence increases by 4 each time, so 17 + 4 = 21." },
  "practice-num-08": { correctIndex: 3, explanation: "Each term is double the preceding term plus 1. Twice 31 plus 1 equals 63." },
  "practice-num-09": { correctIndex: 3, explanation: "Each term is double the preceding term plus 1. Twice 47 plus 1 equals 95." },
  "practice-num-10": { correctIndex: 2, explanation: "Subtract 5 from both sides to get 3x = 15, then divide by 3 to get x = 5." },
  "practice-num-11": { correctIndex: 2, explanation: "Expanding gives 2x + 8 = 3x − 2. Subtracting 2x and adding 2 gives x = 10." },
  "practice-num-12": { correctIndex: 2, explanation: "Five numbers averaging 18 total 90. The missing value is 90 − 68 = 22." },
  "practice-num-13": { correctIndex: 3, explanation: "The ratio has 8 total parts. Blue accounts for 5/8 of 64, which is 40." },
  "practice-ver-04": { correctIndex: 0, explanation: "A bird lives in or builds a nest, while a bee lives in or builds a hive." },
  "practice-ver-05": { correctIndex: 1, explanation: "A scalpel is a characteristic tool of a surgeon; a gavel is a characteristic tool of a judge." },
  "practice-ver-06": { correctIndex: 2, explanation: "Opaque material prevents light from passing through; impermeable material prevents water from passing through." },
  "practice-ver-07": { correctIndex: 1, explanation: "Abundant means plentiful, while scarce means present in an insufficient amount." },
  "practice-ver-08": { correctIndex: 0, explanation: "Meticulous means extremely careful and precise; careless is its closest opposite." },
  "practice-ver-09": { correctIndex: 2, explanation: "To acquiesce is to accept something reluctantly without protest; to resist is to oppose it." },
  "practice-ver-10": { correctIndex: 1, explanation: "Inclement describes unpleasant or severe weather, which explains why an outdoor event was canceled." },
  "practice-ver-11": { correctIndex: 0, explanation: "Despite establishes a contrast: the evidence was compelling, yet the jury remained skeptical." },
  "practice-ver-12": { correctIndex: 1, explanation: "Far from signals a contrast. The criticism was intended to help, so it was not malicious." },
  "practice-ver-13": { correctIndex: 3, explanation: "Apple, pear, plum, and peach are fruits; carrot is a vegetable." },
  "practice-ver-14": { correctIndex: 1, explanation: "Pragmatic means dealing with problems in a practical, realistic way." },
  "practice-ver-15": { correctIndex: 1, explanation: "Obdurate means stubbornly refusing to change an opinion or course of action." },
  "practice-log-03": { correctIndex: 0, explanation: "Every Fen is a Gar, and no Gar is a Tig, so no Fen can be a Tig." },
  "practice-log-04": { correctIndex: 1, explanation: "The Lems that are Pors are Veks, and no Vek is a Dar. Therefore, some Lems are not Dars." },
  "practice-log-05": { correctIndex: 2, explanation: "The statements force the order Ava, then Ben, then Cara, so Cara must arrive last." },
  "practice-log-06": { correctIndex: 1, explanation: "S must precede P, P must precede Q, and Q must precede R, producing S, P, Q, R." },
  "practice-log-07": { correctIndex: 1, explanation: "If an alarm always produces the light, an unlit warning light means the alarm did not sound." },
  "practice-log-08": { correctIndex: 2, explanation: "The letter jumps increase by one: +2, +3, +4, +5, then +6 from P to V." },
  "practice-log-09": { correctIndex: 1, explanation: "If L were selected, N would be selected. Because N is not selected, L is not selected; exactly one rule forces M." },
  "practice-spa-02": { correctIndex: 1, explanation: "A quarter-turn clockwise moves an arrow from north to east." },
  "practice-spa-03": { correctIndex: 3, explanation: "The arrow rotates one quarter-turn clockwise at each step: up, right, down, then left." },
  "practice-spa-04": { correctIndex: 3, explanation: "A vertical mirror reverses left and right, changing an upper-right arrow into an upper-left arrow." },
  "practice-spa-05": { correctIndex: 2, explanation: "The three-shape pattern repeats circle, square, triangle. The sixth shape is therefore a triangle." },
  "practice-spa-06": { correctIndex: 3, explanation: "A 180-degree rotation swaps the shapes' positions and turns the upward triangle downward, producing ○▼." },
};
