import type { AnswerKey } from "./diagnostic";

export const BALANCED_EXPANSION_ANSWER_KEY: AnswerKey = {
  "practice-balanced-ver-01": { correctIndex: 1, explanation: "Austere means severe, plain, or strict in manner or appearance." },
  "practice-balanced-ver-02": { correctIndex: 2, explanation: "To placate someone is to make that person less angry or hostile; calm is the closest meaning." },
  "practice-balanced-ver-03": { correctIndex: 1, explanation: "Perfunctory describes an action done routinely with little care or interest." },
  "practice-balanced-ver-04": { correctIndex: 2, explanation: "A compass measures or indicates direction; a thermometer measures temperature." },
  "practice-balanced-ver-05": { correctIndex: 2, explanation: "Transient means temporary or brief. Permanent is its closest opposite." },
  "practice-balanced-num-01": { correctIndex: 3, explanation: "Output rose by 64 from a starting value of 80. Dividing 64 by 80 gives 0.80, or 80%." },
  "practice-balanced-num-02": { correctIndex: 2, explanation: "The hiring rates are 20%, 25%, 30%, and 20%. Gamma has the highest rate at 30%." },
  "practice-balanced-num-03": { correctIndex: 3, explanation: "Monday had 18 defects and Friday had 5, a decrease of 13." },
  "practice-balanced-num-04": { correctIndex: 2, explanation: "Dividing equal bases subtracts exponents: 5³ ÷ 5¹ = 5² = 25." },
  "practice-balanced-num-05": { correctIndex: 2, explanation: "Circumference equals π times diameter. Using 22/7 × 14 gives 44." },
  "practice-balanced-num-06": { correctIndex: 1, explanation: "Subtracting x + y = 9 from 3x + y = 17 gives 2x = 8, so x = 4." },
  "practice-balanced-num-07": { correctIndex: 3, explanation: "The rule is n² + 2. Four maps to 18, so seven maps to 49 + 2 = 51." },
  "practice-balanced-num-08": { correctIndex: 3, explanation: "Rearranging gives x² - 5x - 24 = 0, which factors as (x - 8)(x + 3). The positive solution is 8." },
  "practice-balanced-log-01": { correctIndex: 4, explanation: "M moves to N, A stays A, T moves to U, and E stays E, producing NAUE." },
  "practice-balanced-log-02": { correctIndex: 0, explanation: "Reversing TONE gives ENOT. Moving the new first letter E forward one gives FNOT." },
  "practice-balanced-log-03": { correctIndex: 3, explanation: "Letter jumps increase by one: +2, +3, +4, then +5 from J to O. Numbers double, so 32 follows 16." },
  "practice-balanced-log-04": { correctIndex: 2, explanation: "Letters move backward by 3, 4, 5, then 6 positions: Z, W, S, N, H. Numbers double to 16." },
  "practice-balanced-log-05": { correctIndex: 4, explanation: "The first four strings read the same forward and backward. IJJK does not." },
  "practice-balanced-log-06": { correctIndex: 3, explanation: "EF731 has exactly two letters followed by three digits, and the final digit 1 is odd." },
  "practice-balanced-spa-01": { correctIndex: 1, explanation: "Each row increases from one symbol to two and then three, so three filled circles complete the second row." },
  "practice-balanced-spa-02": { correctIndex: 0, explanation: "The third cell preserves the first-then-second order. A filled square followed by an outline square gives ■□." },
  "practice-balanced-spa-03": { correctIndex: 1, explanation: "The triangle rotates 90° clockwise each step. After pointing up again, it points right." },
  "practice-balanced-spa-04": { correctIndex: 1, explanation: "One filled square is added to the right at each step, so the next group is a circle followed by four squares." },
  "practice-balanced-spa-05": { correctIndex: 1, explanation: "A vertical mirror reverses the order and flips horizontal direction. ■ ● ◀ becomes ■ ● ▶ in the reflected view." },
  "practice-balanced-spa-06": { correctIndex: 0, explanation: "Southeast is 135° clockwise from north. Rotating 135° counterclockwise therefore points north." },
};
