import type { PracticeQuestion } from "./practice";
import { rotateQuestionChoices } from "./question-choice-rotation";

export const PRIORITY_EXPANSION_QUESTIONS: PracticeQuestion[] = [
  { id: "practice-ver-39", category: "Verbal", prompt: "The instructions were so ___ that even a first-time user completed the setup without help.", choices: ["ambiguous", "lucid", "tedious", "arbitrary", "obsolete"], targetSeconds: 20, difficulty: 1, skill: "sentence completion" },
  { id: "practice-ver-40", category: "Verbal", prompt: "Despite the heavy rain, the outdoor ceremony continued with only a ___ delay.", choices: ["brief", "permanent", "reckless", "complex", "hostile"], targetSeconds: 18, difficulty: 1, skill: "sentence completion" },
  { id: "practice-ver-41", category: "Verbal", prompt: "The scientist repeated the experiment to ___ that the original result was reliable.", choices: ["conceal", "verify", "oppose", "weaken", "postpone"], targetSeconds: 18, difficulty: 1, skill: "sentence completion" },
  { id: "practice-ver-42", category: "Verbal", prompt: "Because the two accounts were nearly identical, the editor suspected that one writer had ___ the other.", choices: ["praised", "copied", "ignored", "interviewed", "corrected"], targetSeconds: 18, difficulty: 1, skill: "sentence completion" },
  { id: "practice-ver-43", category: "Verbal", prompt: "The new evidence did not ___ the theory; instead, it made the theory more convincing.", choices: ["support", "clarify", "undermine", "describe", "repeat"], targetSeconds: 20, difficulty: 1, skill: "sentence completion" },
  { id: "practice-ver-44", category: "Verbal", prompt: "Although the task looked simple, its many exceptions made it surprisingly ___.", choices: ["routine", "intricate", "visible", "popular", "brief"], targetSeconds: 21, difficulty: 2, skill: "sentence completion" },
  { id: "practice-ver-45", category: "Verbal", prompt: "The mediator remained ___, refusing to favor either side in the dispute.", choices: ["impartial", "hostile", "indecisive", "secretive", "impatient"], targetSeconds: 20, difficulty: 2, skill: "sentence completion" },
  { id: "practice-ver-46", category: "Verbal", prompt: "Demand for the product was initially strong but began to ___ once cheaper alternatives appeared.", choices: ["flourish", "stabilize", "wane", "accelerate", "diversify"], targetSeconds: 22, difficulty: 2, skill: "sentence completion" },
  { id: "practice-ver-47", category: "Verbal", prompt: "The witness's calm, detailed statement seemed ___ and therefore worthy of consideration.", choices: ["credible", "random", "hostile", "partial", "vague"], targetSeconds: 21, difficulty: 2, skill: "sentence completion" },
  { id: "practice-ver-48", category: "Verbal", prompt: "Rather than offer a direct refusal, the manager gave an ___ response that left the issue unresolved.", choices: ["explicit", "evasive", "generous", "accurate", "enthusiastic"], targetSeconds: 22, difficulty: 2, skill: "sentence completion" },
  { id: "practice-ver-49", category: "Verbal", prompt: "The charity publishes its accounts annually to ensure complete financial ___.", choices: ["scarcity", "transparency", "discretion", "instability", "uniformity"], targetSeconds: 22, difficulty: 2, skill: "sentence completion" },
  { id: "practice-ver-50", category: "Verbal", prompt: "Her explanation was concise yet ___; it covered every point without unnecessary detail.", choices: ["comprehensive", "tentative", "repetitive", "superficial", "contradictory"], targetSeconds: 22, difficulty: 2, skill: "sentence completion" },
  { id: "practice-ver-51", category: "Verbal", prompt: "The board considered the first estimate too ___ because it ignored several foreseeable expenses.", choices: ["conservative", "optimistic", "precise", "flexible", "ordinary"], targetSeconds: 24, difficulty: 3, skill: "sentence completion" },
  { id: "practice-ver-52", category: "Verbal", prompt: "His apology sounded ___ because he continued to blame everyone except himself.", choices: ["sincere", "insincere", "eloquent", "spontaneous", "concise"], targetSeconds: 22, difficulty: 3, skill: "sentence completion" },
  { id: "practice-ver-53", category: "Verbal", prompt: "The data were too ___ to support a broad conclusion about the entire population.", choices: ["representative", "limited", "consistent", "objective", "abundant"], targetSeconds: 23, difficulty: 3, skill: "sentence completion" },
  { id: "practice-ver-54", category: "Verbal", prompt: "Though once dismissed as impractical, the proposal gained ___ after a successful trial.", choices: ["credibility", "ambiguity", "opposition", "secrecy", "complexity"], targetSeconds: 24, difficulty: 3, skill: "sentence completion" },
  { id: "practice-ver-55", category: "Verbal", prompt: "The lecturer used a familiar example to make an otherwise ___ concept accessible.", choices: ["abstract", "obvious", "popular", "shallow", "irrelevant"], targetSeconds: 23, difficulty: 3, skill: "sentence completion" },
  { id: "practice-ver-56", category: "Verbal", prompt: "The report's neutral language could not disguise its ___ selection of evidence.", choices: ["balanced", "selective", "random", "complete", "generous"], targetSeconds: 25, difficulty: 3, skill: "sentence completion" },
  { id: "practice-ver-57", category: "Verbal", prompt: "Because the deadline was ___, the team postponed all work that was not essential.", choices: ["imminent", "flexible", "distant", "arbitrary", "unknown"], targetSeconds: 23, difficulty: 3, skill: "sentence completion" },
  { id: "practice-ver-58", category: "Verbal", prompt: "The apparent contradiction was ___ when the researchers discovered that the studies used different definitions.", choices: ["deepened", "resolved", "ignored", "predicted", "concealed"], targetSeconds: 24, difficulty: 3, skill: "sentence completion" },
  { id: "practice-ver-59", category: "Verbal", prompt: "The candidate's answers were polished but ___, revealing little about her actual position.", choices: ["candid", "substantive", "formulaic", "incisive", "spontaneous"], targetSeconds: 26, difficulty: 4, skill: "sentence completion" },
  { id: "practice-ver-60", category: "Verbal", prompt: "What appeared to be a generous concession was actually a ___ attempt to delay the negotiations.", choices: ["magnanimous", "transparent", "calculated", "haphazard", "conciliatory"], targetSeconds: 27, difficulty: 4, skill: "sentence completion" },
  { id: "practice-ver-61", category: "Verbal", prompt: "The policy was intended as a temporary measure, but it gradually became ___.", choices: ["entrenched", "sporadic", "tentative", "negligible", "obsolete"], targetSeconds: 27, difficulty: 4, skill: "sentence completion" },
  { id: "practice-ver-62", category: "Verbal", prompt: "The critic's praise was so ___ that readers could not tell whether it was sincere or ironic.", choices: ["effusive", "equivocal", "measured", "factual", "restrained"], targetSeconds: 28, difficulty: 4, skill: "sentence completion" },
  { id: "practice-ver-63", category: "Verbal", prompt: "The executive's ___ response addressed the immediate complaint while avoiding the larger issue.", choices: ["exhaustive", "perfunctory", "visionary", "candid", "impartial"], targetSeconds: 28, difficulty: 4, skill: "sentence completion" },
  { id: "practice-ver-64", category: "Verbal", prompt: "Even the strongest evidence failed to ___ the skeptic, whose position had become inflexible.", choices: ["placate", "persuade", "confuse", "provoke", "imitate"], targetSeconds: 26, difficulty: 4, skill: "sentence completion" },
  { id: "practice-ver-65", category: "Verbal", prompt: "The historian warned that the seemingly ___ trend might be an artifact of incomplete records.", choices: ["unequivocal", "negligible", "sporadic", "benign", "obsolete"], targetSeconds: 29, difficulty: 4, skill: "sentence completion" },
  { id: "practice-ver-66", category: "Verbal", prompt: "Her argument was elegant but ultimately ___, since its conclusion merely restated its premise.", choices: ["empirical", "circular", "nuanced", "pragmatic", "lucid"], targetSeconds: 30, difficulty: 5, skill: "sentence completion" },
  { id: "practice-ver-67", category: "Verbal", prompt: "The spokesperson's carefully worded statement was designed to ___ responsibility without making a demonstrably false claim.", choices: ["assume", "disavow", "clarify", "publicize", "allocate"], targetSeconds: 30, difficulty: 5, skill: "sentence completion" },
  { id: "practice-ver-68", category: "Verbal", prompt: "Although the findings were statistically significant, their practical effect was so ___ that the policy remained unchanged.", choices: ["profound", "negligible", "pervasive", "volatile", "conclusive"], targetSeconds: 30, difficulty: 5, skill: "sentence completion" },
  { id: "practice-ver-69", category: "Verbal", prompt: "The author's apparently ___ tone masks a sustained critique that becomes clear only on close reading.", choices: ["dispassionate", "vitriolic", "dogmatic", "sentimental", "credulous"], targetSeconds: 32, difficulty: 5, skill: "sentence completion" },
  { id: "practice-ver-70", category: "Verbal", prompt: "By presenting an exception as if it were typical, the article offers a ___ account of the evidence.", choices: ["scrupulous", "distorted", "comprehensive", "tentative", "redundant"], targetSeconds: 29, difficulty: 5, skill: "sentence completion" },
  { id: "practice-ver-71", category: "Verbal", prompt: "The negotiator's deliberate silence was not indecision but a ___ tactic intended to draw out the other side.", choices: ["strategic", "capricious", "submissive", "peripheral", "retrospective"], targetSeconds: 29, difficulty: 4, skill: "sentence completion" },
  { id: "practice-ver-72", category: "Verbal", prompt: "Because the rule admits so many exceptions, its usefulness as a predictive principle is ___.", choices: ["enhanced", "questionable", "universal", "self-evident", "unprecedented"], targetSeconds: 28, difficulty: 4, skill: "sentence completion" },
  { id: "practice-ver-73", category: "Verbal", prompt: "The analyst distinguished between a temporary fluctuation and a ___ shift in consumer behavior.", choices: ["structural", "momentary", "random", "superficial", "reversible"], targetSeconds: 27, difficulty: 4, skill: "sentence completion" },

  ...pairQuestions(),
].map((question) => rotateQuestionChoices(question as PracticeQuestion));

function pairQuestions(): PracticeQuestion[] {
  const specs: Array<[string, string, 1 | 2 | 3 | 4 | 5, Array<[string, string]>]> = [
    ["practice-ver-74", "How many customer IDs are exactly the same in both columns?", 1, [["A14", "A14"], ["B27", "B72"], ["C39", "C39"], ["D42", "D42"], ["E58", "E85"]]],
    ["practice-ver-75", "How many short product codes match exactly?", 1, [["KT-21", "KT-21"], ["LM-44", "LN-44"], ["PQ-07", "PQ-07"], ["RS-63", "RS-36"], ["VX-90", "VX-90"]]],
    ["practice-ver-76", "Count the identical reference pairs.", 1, [["4108", "4108"], ["5726", "5726"], ["6381", "6831"], ["7045", "7045"], ["9962", "9926"]]],
    ["practice-ver-77", "How many employee codes are exact matches?", 2, [["AR7-31", "AR7-31"], ["BT5-82", "BT5-28"], ["CM9-46", "CM9-46"], ["DP2-75", "DPZ-75"], ["EF8-19", "EF8-19"]]],
    ["practice-ver-78", "How many invoice references match character for character?", 2, [["IV-2048", "IV-2048"], ["IV-3167", "IV-3617"], ["IV-4290", "IV-4290"], ["IV-5381", "1V-5381"], ["IV-6452", "IV-6452"]]],
    ["practice-ver-79", "Count the perfectly matching serial-number rows.", 2, [["SN84-K2", "SN84-K2"], ["SN19-Q7", "SN19-07"], ["SN63-M4", "SN63-M4"], ["SN27-P8", "SN72-P8"], ["SN55-R1", "SN55-R1"]]],
    ["practice-ver-80", "How many account labels are reproduced without an error?", 2, [["AC-711-B", "AC-711-B"], ["AC-826-D", "AC-826-O"], ["AC-934-F", "AC-934-F"], ["AC-148-H", "AC-184-H"], ["AC-259-K", "AC-259-K"]]],
    ["practice-ver-81", "How many shipment codes are identical across the two lists?", 2, [["SH8-401", "SH8-401"], ["SH3-762", "SH3-726"], ["SH9-185", "SH9-185"], ["SH4-630", "SH4-G30"], ["SH7-294", "SH7-294"]]],
    ["practice-ver-82", "Count the rows with no letter, digit, or position change.", 3, [["QX4-819", "QX4-819"], ["MN7-260", "MN7-2G0"], ["RT2-543", "RT2-543"], ["BV9-176", "BV9-167"], ["LP5-808", "LP5-808"]]],
    ["practice-ver-83", "How many registry entries match exactly?", 3, [["RG-42-AX", "RG-42-AX"], ["RG-73-BM", "RG-73-BN"], ["RG-18-CP", "RG-81-CP"], ["RG-56-DQ", "RG-56-DQ"], ["RG-90-EV", "RG-90-EV"]]],
    ["practice-ver-84", "How many paired access keys are exact duplicates?", 3, [["7KT-41P", "7KT-41P"], ["3LM-86Q", "3LN-86Q"], ["9RX-20B", "9RX-20B"], ["5DV-73C", "5DV-37C"], ["2HN-64F", "2HN-64F"]]],
    ["practice-ver-85", "Count the matching inventory identifiers.", 3, [["IN4-X-208", "IN4-X-208"], ["IN7-M-631", "IN7-N-631"], ["IN2-Q-954", "IN2-Q-945"], ["IN8-B-417", "IN8-B-417"], ["IN5-R-780", "IN5-R-780"]]],
    ["practice-ver-86", "How many case references remain unchanged?", 3, [["CS-81A-42", "CS-81A-42"], ["CS-37B-95", "CS-37B-59"], ["CS-64D-18", "CS-64O-18"], ["CS-29F-73", "CS-29F-73"], ["CS-55H-06", "CS-55H-06"]]],
    ["practice-ver-87", "How many transaction strings match in every position?", 3, [["TX6-204-K", "TX6-204-K"], ["TX8-731-M", "TX8-713-M"], ["TX2-956-P", "TX2-956-P"], ["TX9-418-R", "TX9-41B-R"], ["TX4-680-V", "TX4-680-V"]]],
    ["practice-ver-88", "Count the exact matches in this document-control check.", 3, [["DC-4Q-821", "DC-4Q-821"], ["DC-7T-305", "DC-7T-350"], ["DC-2V-964", "DC-2V-964"], ["DC-9X-176", "DC-9X-I76"], ["DC-5Z-438", "DC-5Z-438"]]],
    ["practice-ver-89", "How many long-form order codes are identical?", 4, [["OR8-41M-762", "OR8-41M-762"], ["OR5-93B-147", "OR5-938-147"], ["OR2-67Q-805", "OR2-67Q-850"], ["OR9-24T-631", "OR9-24T-631"], ["OR3-58V-409", "OR3-58V-409"]]],
    ["practice-ver-90", "Count the flawless matches in the archive index.", 4, [["AR-7K2-8401", "AR-7K2-8401"], ["AR-3M8-1765", "AR-3M8-1675"], ["AR-9P4-5206", "AR-9P4-5206"], ["AR-2Q7-9384", "AR-2O7-9384"], ["AR-6V1-3049", "AR-6V1-3049"]]],
    ["practice-ver-91", "How many compliance-record pairs match exactly?", 4, [["CP8-A41-209", "CP8-A41-209"], ["CP3-D76-815", "CP3-D76-81S"], ["CP9-F20-634", "CP9-F02-634"], ["CP5-H83-471", "CP5-H83-471"], ["CP2-K59-308", "CP2-K59-308"]]],
    ["practice-ver-92", "Count the unchanged laboratory sample IDs.", 4, [["LB-81Q-4X2", "LB-81Q-4X2"], ["LB-36T-9M5", "LB-36T-9N5"], ["LB-74V-2P8", "LB-47V-2P8"], ["LB-59B-7R1", "LB-59B-7R1"], ["LB-20D-6K4", "LB-20D-6K4"]]],
    ["practice-ver-93", "How many routing strings are perfect matches?", 4, [["RT7-4A9-260", "RT7-4A9-260"], ["RT2-8C5-731", "RT2-8C5-713"], ["RT9-1F6-408", "RT9-IF6-408"], ["RT3-7H2-954", "RT3-7H2-954"], ["RT5-0K8-317", "RT5-0K8-317"]]],
    ["practice-ver-94", "Count the exact matches among these dense identifiers.", 4, [["8QK-41M-762P", "8QK-41M-762P"], ["5RB-903-X17N", "5RB-930-X17N"], ["6TN-28G-445C", "6TN-28G-445C"], ["LP4-771-Z09V", "LP4-771-ZO9V"], ["3DV-618-K52H", "3DV-618-K52H"]]],
    ["practice-ver-95", "How many securities references are identical character by character?", 5, [["SC8-41M7-620P", "SC8-41M7-620P"], ["SC5-93B0-147N", "SC5-9380-147N"], ["SC2-67Q4-805C", "SC2-67Q4-850C"], ["SC9-24T8-631V", "SC9-24T8-631V"], ["SC3-58V1-409H", "SC3-58V1-409H"]]],
    ["practice-ver-96", "Count the exact matches in this high-density audit.", 5, [["HD-7K2A-8401Q", "HD-7K2A-8401Q"], ["HD-3M8D-1765T", "HD-3M8D-1675T"], ["HD-9P4F-5206V", "HD-9P4F-5206V"], ["HD-2Q7H-9384B", "HD-2O7H-9384B"], ["HD-6V1K-3049D", "HD-6V1K-3049D"]]],
    ["practice-ver-97", "How many multi-part credentials match without any discrepancy?", 5, [["CR8-A41-Q209-X", "CR8-A41-Q209-X"], ["CR3-D76-T815-M", "CR3-D76-T81S-M"], ["CR9-F20-V634-P", "CR9-F02-V634-P"], ["CR5-H83-B471-R", "CR5-H83-B471-R"], ["CR2-K59-D308-W", "CR2-K59-D308-W"]]],
    ["practice-ver-98", "Count the perfectly duplicated forensic labels.", 5, [["FR-81Q4-X2A7", "FR-81Q4-X2A7"], ["FR-36T9-M5C2", "FR-36T9-N5C2"], ["FR-74V2-P8F6", "FR-47V2-P8F6"], ["FR-59B7-R1H3", "FR-59B7-R1H3"], ["FR-20D6-K4L9", "FR-20D6-K4L9"]]],
  ];
  const desiredMatches = [2, 4, 1, 3, 5, 1, 4, 2, 5, 3, 2, 1, 4, 3, 5, 4, 2, 5, 1, 3, 5, 3, 1, 4, 2];
  return specs.map(([id, prompt, difficulty, pairs], specIndex) => {
    const matchingPositions = new Set(Array.from({ length: desiredMatches[specIndex] }, (_, offset) => (specIndex * 2 + offset * 2) % 5));
    const variedPairs = pairs.map(([left, right], pairIndex): [string, string] => matchingPositions.has(pairIndex)
      ? [left, left]
      : [left, right === left ? `${left.slice(0, -1)}X` : right]);
    return { id, category: "Verbal", prompt, choices: ["1", "2", "3", "4", "5"], targetSeconds: 18 + difficulty * 3, difficulty, skill: "attention to detail", stimulus: { kind: "pairs", title: "Compare each row", pairs: variedPairs } };
  });
}
