import { PRACTICE_EXPANSION_ANSWER_KEY } from "./practice-expansion-bank.server";
import { PRIORITY_EXPANSION_ANSWER_KEY } from "./practice-expansion-priority-bank.server";
import { ADVANCED_MATH_ANSWER_KEY } from "./practice-expansion-math-bank.server";
import { LOGIC_SPATIAL_EXPANSION_ANSWER_KEY } from "./practice-expansion-logic-spatial-bank.server";
import { TOPIC_EXPANSION_ANSWER_KEY } from "./practice-expansion-topics-bank.server";
import { THIN_SKILL_EXPANSION_ANSWER_KEY } from "./practice-expansion-thin-skills-bank.server";

export const PRACTICE_ANSWER_KEY: Record<string, { correctIndex: number; explanation: string }> = {
  ...PRACTICE_EXPANSION_ANSWER_KEY,
  ...PRIORITY_EXPANSION_ANSWER_KEY,
  ...ADVANCED_MATH_ANSWER_KEY,
  ...LOGIC_SPATIAL_EXPANSION_ANSWER_KEY,
  ...TOPIC_EXPANSION_ANSWER_KEY,
  ...THIN_SKILL_EXPANSION_ANSWER_KEY,
  "practice-num-01": { correctIndex: 2, explanation: "Each machine produces 10 parts per hour. Eight machines working for five hours produce 8 × 5 × 10 = 400 parts." },
  "practice-ver-01": { correctIndex: 1, explanation: "Transparent and opaque are opposites. Flexible and rigid have the same opposite relationship." },
  "practice-log-01": { correctIndex: 2, explanation: "The first statement directly guarantees that every Nib is a Pex. The overlap between Pexes and Jors does not establish anything further about Nibs." },
  "practice-num-02": { correctIndex: 3, explanation: "Each term is the previous term doubled plus 2. Therefore, 78 × 2 + 2 = 158." },
  "practice-spa-01": { correctIndex: 1, explanation: "West turned 270° clockwise points south. Turning 90° counterclockwise from south points east." },
  "practice-ver-02": { correctIndex: 2, explanation: "Concise means brief and economical with words. Verbose means using more words than necessary." },
  "practice-log-02": { correctIndex: 2, explanation: "The order includes Mara before Theo before Jin before Sal, so both Mara and Theo must arrive before Jin." },
  "practice-num-03": { correctIndex: 1, explanation: "The increase is 30. Dividing 30 by the original 120 gives 0.25, or 25%." },
  "practice-ver-03": { correctIndex: 1, explanation: "Although signals a contrast: the evidence was initially inconclusive, but later findings made the conclusion nearly certain." },
  "practice-num-04": { correctIndex: 2, explanation: "Each box holds 4 files, so five identical boxes hold 5 × 4 = 20 files." },
  "practice-num-05": { correctIndex: 2, explanation: "Fifteen percent of $120 is $18. Subtracting $18 from $120 gives a $102 sale price." },
  "practice-num-06": { correctIndex: 2, explanation: "A 20% increase takes $200 to $240. Reducing $240 by 25% subtracts $60, leaving $180." },
  "practice-num-07": { correctIndex: 2, explanation: "The sequence increases by 4 each time, so 17 + 4 = 21." },
  "practice-num-08": { correctIndex: 3, explanation: "Each term is double the preceding term plus 1. Twice 31 plus 1 equals 63." },
  "practice-num-09": { correctIndex: 3, explanation: "Each term is double the preceding term plus 1. Twice 47 plus 1 equals 95." },
  "practice-num-10": { correctIndex: 2, explanation: "Subtract 5 from both sides to get 3x = 15, then divide by 3 to get x = 5." },
  "practice-num-11": { correctIndex: 2, explanation: "Expanding gives 2x + 8 = 3x − 2. Subtracting 2x and adding 2 gives x = 10." },
  "practice-num-12": { correctIndex: 2, explanation: "Five numbers averaging 18 total 90. The missing value is 90 − 68 = 22." },
  "practice-num-13": { correctIndex: 3, explanation: "The ratio has 8 total parts. Blue accounts for 5/8 of 64, which is 40." },
  "practice-ver-04": { correctIndex: 0, explanation: "A bird lives in or builds a nest, while a bee lives in or builds a hive." },
  "practice-ver-05": { correctIndex: 1, explanation: "A scalpel is a characteristic tool of a surgeon; a gavel is a characteristic tool of a judge." },
  "practice-ver-06": { correctIndex: 2, explanation: "Opaque material prevents light from passing through; impermeable material prevents water from passing through." },
  "practice-ver-07": { correctIndex: 1, explanation: "Abundant means plentiful, while scarce means present in an insufficient amount." },
  "practice-ver-08": { correctIndex: 0, explanation: "Meticulous means extremely careful and precise; careless is its closest opposite." },
  "practice-ver-09": { correctIndex: 2, explanation: "To acquiesce is to accept something reluctantly without protest; to resist is to oppose it." },
  "practice-ver-10": { correctIndex: 1, explanation: "Inclement describes unpleasant or severe weather, which explains why an outdoor event was canceled." },
  "practice-ver-11": { correctIndex: 0, explanation: "Despite establishes a contrast: the evidence was compelling, yet the jury remained skeptical." },
  "practice-ver-12": { correctIndex: 1, explanation: "Far from signals a contrast. The criticism was intended to help, so it was not malicious." },
  "practice-ver-13": { correctIndex: 3, explanation: "Apple, pear, plum, and peach are fruits; carrot is a vegetable." },
  "practice-ver-14": { correctIndex: 1, explanation: "Pragmatic means dealing with problems in a practical, realistic way." },
  "practice-ver-15": { correctIndex: 1, explanation: "Obdurate means stubbornly refusing to change an opinion or course of action." },
  "practice-log-03": { correctIndex: 0, explanation: "Every Fen is a Gar, and no Gar is a Tig, so no Fen can be a Tig." },
  "practice-log-04": { correctIndex: 1, explanation: "The Lems that are Pors are Veks, and no Vek is a Dar. Therefore, some Lems are not Dars." },
  "practice-log-05": { correctIndex: 2, explanation: "The statements force the order Ava, then Ben, then Cara, so Cara must arrive last." },
  "practice-log-06": { correctIndex: 1, explanation: "S must precede P, P must precede Q, and Q must precede R, producing S, P, Q, R." },
  "practice-log-07": { correctIndex: 1, explanation: "If an alarm always produces the light, an unlit warning light means the alarm did not sound." },
  "practice-log-08": { correctIndex: 2, explanation: "The letter jumps increase by one: +2, +3, +4, +5, then +6 from P to V." },
  "practice-log-09": { correctIndex: 1, explanation: "If L were selected, N would be selected. Because N is not selected, L is not selected; exactly one rule forces M." },
  "practice-spa-02": { correctIndex: 1, explanation: "A quarter-turn clockwise moves an arrow from north to east." },
  "practice-spa-03": { correctIndex: 3, explanation: "The arrow rotates one quarter-turn clockwise at each step: up, right, down, then left." },
  "practice-spa-04": { correctIndex: 3, explanation: "A vertical mirror reverses left and right, changing an upper-right arrow into an upper-left arrow." },
  "practice-spa-05": { correctIndex: 2, explanation: "The three-shape pattern repeats circle, square, triangle. The sixth shape is therefore a triangle." },
  "practice-spa-06": { correctIndex: 3, explanation: "A 180-degree rotation swaps the shapes' positions and turns the upward triangle downward, producing ○▼." },
  "practice-num-14": { correctIndex: 1, explanation: "Add 10 and 14 to get 24, then divide by two values to get an average of 12." },
  "practice-num-15": { correctIndex: 2, explanation: "Six numbers averaging 23 have a total of 138. Subtracting the known total of 111 leaves 27." },
  "practice-num-16": { correctIndex: 3, explanation: "The groups completed 72 and 162 tasks. Their combined 234 tasks divided among 10 workers gives 23.4." },
  "practice-num-17": { correctIndex: 2, explanation: "Three-fourths equals 0.75, which exceeds 0.70, about 0.667, 0.625, and 0.50." },
  "practice-num-18": { correctIndex: 3, explanation: "One-third of 45 is 15, so two-thirds is twice that amount, or 30." },
  "practice-num-19": { correctIndex: 2, explanation: "The unfilled portion is 5/12. Five-twelfths of 144 liters equals 60 liters." },
  "practice-log-10": { correctIndex: 1, explanation: "The letters advance by two positions each time: A, C, E, G, then I." },
  "practice-log-11": { correctIndex: 1, explanation: "The first letter moves forward while the second moves backward: A-Z, B-Y, C-X, then D-W." },
  "practice-log-12": { correctIndex: 2, explanation: "The starting letters jump by 3, 4, 5, then 6 positions: A, D, H, M, S. Each pair uses consecutive letters, so ST follows." },
  "practice-spa-07": { correctIndex: 3, explanation: "A vertical reflection reverses horizontal direction, so a right-pointing arrow appears to point left." },
  "practice-spa-08": { correctIndex: 2, explanation: "A vertical reflection preserves downward direction but reverses right to left, changing ↘ into ↙." },
  "practice-spa-09": { correctIndex: 1, explanation: "A vertical mirror reverses the order of the three horizontally arranged symmetric shapes, producing ■○▲." },
  "practice-ver-16": { correctIndex: 3, explanation: "Dog, cat, horse, and rabbit are animals. Tulip is a flowering plant." },
  "practice-ver-17": { correctIndex: 3, explanation: "Copper, iron, silver, and gold are metals. Granite is a type of rock." },
  "practice-ver-18": { correctIndex: 3, explanation: "Taciturn, reticent, laconic, and reserved indicate limited speech. Verbose means using many words." },
  "practice-num-20": { correctIndex: 3, explanation: "Output increased by 60 from an original 80. Sixty divided by 80 equals 75%." },
  "practice-num-21": { correctIndex: 3, explanation: "The hiring rates are 20%, 25%, 20%, and 30%. West has the highest rate at 30%." },
  "practice-num-22": { correctIndex: 2, explanation: "Tuesday is 20 minutes and Thursday is 16 minutes. Their average is 18 minutes." },
  "practice-num-23": { correctIndex: 2, explanation: "Sales exceeds Administration by 20 percentage points. Twenty percent of $360,000 is $72,000." },
  "practice-ver-19": { correctIndex: 2, explanation: "Only B4X66L is reproduced without a transposition, substitution, or changed character." },
  "practice-ver-20": { correctIndex: 2, explanation: "Rows 1, 3, and 5 match exactly. Rows 2 and 4 contain a transposition or substitution, so 3 rows match." },
  "practice-ver-21": { correctIndex: 2, explanation: "Only 6TN-28G-445 is identical on both sides. Every other option contains a changed or transposed character." },
  "practice-spa-10": { correctIndex: 2, explanation: "Each row increases from one symbol to two and then three, so three filled squares complete the bottom row." },
  "practice-spa-11": { correctIndex: 2, explanation: "The third cell combines the outline and filled versions from the first two cells, producing □■." },
  "practice-spa-12": { correctIndex: 1, explanation: "Rotating a left arrow 90 degrees clockwise makes it point up. Placing it before the square gives ↑□." },
};
