import type { AnswerKey } from "./diagnostic";

export const DIAGNOSTIC_ANSWER_KEY: AnswerKey = {
  "num-01": { correctIndex: 2, explanation: "Forty hours contains five 8-hour blocks. Five blocks multiplied by 3 reports equals 15." },
  "ver-01": { correctIndex: 1, explanation: "Frail and sturdy are opposites. Scarce and plentiful have the same opposite relationship." },
  "log-01": { correctIndex: 0, explanation: "Because every Kem is a Ral and no Ral can be a Tov, no Kem can be a Tov." },
  "num-02": { correctIndex: 3, explanation: "Each number is the previous number doubled minus 1. Therefore, 49 × 2 − 1 = 97." },
  "spa-01": { correctIndex: 1, explanation: "The triangle rotates one quarter-turn clockwise at each step: up, right, down, then left." },
  "ver-02": { correctIndex: 1, explanation: "Promising creates the contrast with the rejection, while flawed explains why the committee rejected the proposal despite its promise." },
  "log-02": { correctIndex: 1, explanation: "The first two statements establish Liam > Noor > Priya, so Priya cannot be older than Liam." },
  "num-03": { correctIndex: 2, explanation: "The discounted price is $60. Increasing $60 by 10% adds $6, producing a final price of $66." },
  "ver-03": { correctIndex: 0, explanation: "Equivocal means ambiguous or open to more than one interpretation." },
  "num-04": { correctIndex: 1, explanation: "Each printer produces 10 pages per minute. Four printers working for 10 minutes produce 400 pages." },
  "spa-02": { correctIndex: 4, explanation: "The first four choices pair a circle with a triangle pointing in one of four directions. The diamond breaks that rule." },
  "ver-04": { correctIndex: 1, explanation: "Something ephemeral has little duration; something fragile has little durability." },
  "num-05": { correctIndex: 3, explanation: "Two-thirds is about 0.667, which is larger than 0.625, 0.60, 0.583, and 0.563." },
  "log-03": { correctIndex: 1, explanation: "The Vens that are Lops must also be Mirs because every Lop is a Mir." },
  "ver-05": { correctIndex: 1, explanation: "To mitigate is to make something less severe; to aggravate is to make it more severe." },
  "num-06": { correctIndex: 2, explanation: "The increases are 4, 6, 8, and 10. The next increase is 12, giving 42." },
  "spa-03": { correctIndex: 2, explanation: "In each row, the third cell combines the outline shape and filled shape from the first two cells. The answer is outline square plus filled square." },
  "ver-06": { correctIndex: 2, explanation: "A conductor directs an orchestra, while a director directs a cast." },
  "num-07": { correctIndex: 2, explanation: "Four pumps for 6 hours is 24 pump-hours for 3 tanks, or 8 pump-hours per tank. Seventy-two pump-hours fills 9 tanks." },
  "log-04": { correctIndex: 0, explanation: "The conditions force Tarek before Rina before Sol before Uma, matching only the first order." },
  "ver-07": { correctIndex: 3, explanation: "Rows 1, 3, and 5 match exactly. Rows 2 and 4 contain transposed final digits, so 3 pairs are the same." },
  "num-08": { correctIndex: 2, explanation: "Expanding gives 2x minus 6 equals 3x minus 11, so x equals 5 and 4x equals 20." },
  "spa-04": { correctIndex: 1, explanation: "The shaded half rotates one quarter-turn clockwise through left, top, right, and then bottom." },
  "ver-08": { correctIndex: 3, explanation: "Taciturn, reticent, reserved, and uncommunicative describe quietness; garrulous means excessively talkative." },
  "num-09": { correctIndex: 3, explanation: "Output rose from 120 to 180, an increase of 60. Sixty divided by the original 120 equals 50%." },
  "log-05": { correctIndex: 0, explanation: "The Ruds that are Naks are also Pims because every Rud is a Pim, so some Pims are Naks." },
  "ver-09": { correctIndex: 1, explanation: "Temporary and permanent are opposites, as are shallow and deep." },
  "num-10": { correctIndex: 2, explanation: "Tuesday is 20 minutes and Thursday is 16 minutes. Their average is 18 minutes." },
  "spa-05": { correctIndex: 0, explanation: "A vertical reflection reverses left and right. The arrow points upper-left, and the circle appears to its left in the reflected image." },
  "ver-10": { correctIndex: 3, explanation: "Only P4X72N is reproduced without a substituted, transposed, or missing character." },
  "num-11": { correctIndex: 2, explanation: "The increases double: 1, 2, 4, and 8. Adding the next increase of 16 gives 33." },
  "log-06": { correctIndex: 1, explanation: "Every Kim is a Zet, and no Zet is a Far, so no Kim can be a Far." },
  "ver-11": { correctIndex: 1, explanation: "A seed develops into a plant, while an egg develops into a bird." },
  "num-12": { correctIndex: 2, explanation: "A 20% increase followed by a 20% decrease multiplies the original by 1.2 times 0.8, or 0.96. Ninety-six divided by 0.96 is 100." },
  "spa-06": { correctIndex: 2, explanation: "Both rows rotate their directional feature one quarter-turn clockwise: up, right, then down. The bottom-shaded semicircle completes the row." },
  "ver-12": { correctIndex: 2, explanation: "Obscure can mean unclear or hidden; clear is its closest opposite." },
  "num-13": { correctIndex: 2, explanation: "Operations exceeds Administration by 20 percentage points. Twenty percent of $240,000 is $48,000." },
  "log-07": { correctIndex: 2, explanation: "The statements establish Nia above Milo above Jae above Kira, so Milo ranks second." },
  "ver-13": { correctIndex: 4, explanation: "The first four choices preserve the same outline triangle-and-circle arrangement under rotation. The last replaces the outline circle with a filled one." },
  "num-14": { correctIndex: 2, explanation: "The hiring rates are 25%, 20%, 30%, and 20%. East has the highest rate at 30%." },
  "log-08": { correctIndex: 0, explanation: "Each pair begins with the second shape from the preceding pair. After triangle-diamond, the next pair must begin diamond-circle." },
  "ver-14": { correctIndex: 1, explanation: "Only rows 1 and 4 match exactly. The other rows contain a transposition or a single-character substitution, so 2 pairs are the same." },
  "num-15": { correctIndex: 2, explanation: "The three-state cycle is filled circle, ringed circle, outline circle. The sixth position repeats the outline circle." },
  "log-09": { correctIndex: 3, explanation: "The Wiks that are Bors may or may not be Dels, so nothing definite follows about Dels and Bors." },
  "ver-15": { correctIndex: 2, explanation: "A barometer records atmospheric pressure, while a seismograph records earthquake motion." },
  "num-16": { correctIndex: 2, explanation: "The letter-position jumps increase by one: plus 2, 3, 4, and 5. The next jump is plus 6, taking O to U." },
  "log-10": { correctIndex: 2, explanation: "M J K L places K after J and M before L, satisfying both rules." },
  "ver-16": { correctIndex: 1, explanation: "Equivocal means deliberately ambiguous. That meaning explains why investigators could not determine what had occurred." },
  "num-17": { correctIndex: 3, explanation: "The arrow rotates one quarter-turn clockwise each time: upper-left, upper-right, lower-right, then lower-left." },
  "num-18": { correctIndex: 3, explanation: "Expanding gives 3y plus 2 equals 2y plus 14, so y equals 12. Five times 12 minus 3 is 57." },
};
