import type { AnswerKey } from "./diagnostic";

export const DIAGNOSTIC_ANSWER_KEY: AnswerKey = {
  "num-01": { correctIndex: 2, explanation: "Forty hours contains five 8-hour blocks. Five blocks multiplied by 3 reports equals 15." },
  "ver-01": { correctIndex: 1, explanation: "Frail and sturdy are opposites. Scarce and plentiful have the same opposite relationship." },
  "log-01": { correctIndex: 0, explanation: "Because every Kem is a Ral and no Ral can be a Tov, no Kem can be a Tov." },
  "num-02": { correctIndex: 3, explanation: "Each number is the previous number doubled minus 1. Therefore, 49 × 2 − 1 = 97." },
  "spa-01": { correctIndex: 4, explanation: "North rotated clockwise 90° becomes east. East rotated counterclockwise 180° becomes west." },
  "ver-02": { correctIndex: 3, explanation: "Conclude, infer, deduce, and reason involve deriving a judgment. Observe means to notice directly." },
  "log-02": { correctIndex: 1, explanation: "The first two statements establish Liam > Noor > Priya, so Priya cannot be older than Liam." },
  "num-03": { correctIndex: 2, explanation: "The discounted price is $60. Increasing $60 by 10% adds $6, producing a final price of $66." },
  "ver-03": { correctIndex: 0, explanation: "Benevolent means kind, charitable, or well-meaning." },
  "num-04": { correctIndex: 2, explanation: "Thirty-five percent of 240 is 0.35 multiplied by 240, which equals 84." },
  "spa-02": { correctIndex: 3, explanation: "A half-turn swaps both top with bottom and left with right, moving the dot to the lower-right corner." },
  "ver-04": { correctIndex: 1, explanation: "A flock is a group of birds, while a school is a group of fish." },
  "num-05": { correctIndex: 3, explanation: "Two-thirds is about 0.667, which is larger than 0.625, 0.60, 0.583, and 0.563." },
  "log-03": { correctIndex: 1, explanation: "The Vens that are Lops must also be Mirs because every Lop is a Mir." },
  "ver-05": { correctIndex: 1, explanation: "To expand is to grow or enlarge; to contract is to shrink." },
  "num-06": { correctIndex: 2, explanation: "The increases are 4, 6, 8, and 10. The next increase is 12, giving 42." },
  "spa-03": { correctIndex: 3, explanation: "From south, a left turn faces east. Two right turns then face south and finally west." },
  "ver-06": { correctIndex: 2, explanation: "A doctor typically works in a hospital, and a teacher typically works in a school." },
  "num-07": { correctIndex: 2, explanation: "The rate is 50 miles per hour. Five hours at that rate covers 250 miles." },
  "log-04": { correctIndex: 0, explanation: "Ana is before Bo, and Bo is before Cal, so Ana must finish first." },
  "ver-07": { correctIndex: 1, explanation: "Meticulous means very careful, precise, and thorough." },
  "num-08": { correctIndex: 3, explanation: "Subtracting 7 gives x = 12, and 3 times 12 equals 36." },
  "spa-04": { correctIndex: 3, explanation: "Three clockwise quarter-turns move the point from up to right, down, and then left." },
  "ver-08": { correctIndex: 3, explanation: "Copper, iron, silver, and gold are metals; glass is not." },
  "num-09": { correctIndex: 3, explanation: "Fifteen percent of $60 is $9. Subtracting $9 gives a sale price of $51." },
  "log-05": { correctIndex: 0, explanation: "The Ruds that are Naks are also Pims because every Rud is a Pim, so some Pims are Naks." },
  "ver-09": { correctIndex: 1, explanation: "Temporary and permanent are opposites, as are shallow and deep." },
  "num-10": { correctIndex: 2, explanation: "The sum is 80. Dividing by four values gives an average of 20." },
  "spa-05": { correctIndex: 3, explanation: "A half-turn moves the minute hand from 3 to the opposite position at 9." },
  "ver-10": { correctIndex: 1, explanation: "Frugal means economical or careful about spending resources." },
  "num-11": { correctIndex: 1, explanation: "Each term is divided by 3, so 3 divided by 3 equals 1." },
  "log-06": { correctIndex: 1, explanation: "Every Kim is a Zet, and no Zet is a Far, so no Kim can be a Far." },
  "ver-11": { correctIndex: 1, explanation: "A seed develops into a plant, while an egg develops into a bird." },
  "num-12": { correctIndex: 2, explanation: "Each notebook costs $2.50. Ten notebooks therefore cost $25." },
  "spa-06": { correctIndex: 1, explanation: "The two rightward and two leftward moves cancel, leaving the shape one space down." },
  "ver-12": { correctIndex: 2, explanation: "Obscure can mean unclear or hidden; clear is its closest opposite." },
  "num-13": { correctIndex: 3, explanation: "There are 10 balls total and 5 are blue, so the fraction is 5/10, or 1/2." },
  "log-07": { correctIndex: 0, explanation: "Dara is taller than Eli, and Eli is taller than Finn, making Dara tallest." },
  "ver-13": { correctIndex: 2, explanation: "Whisper, murmur, mumble, and mutter describe quiet speech; shout does not." },
  "num-14": { correctIndex: 2, explanation: "Seven squared is 49 and five squared is 25. Their difference is 24." },
  "log-08": { correctIndex: 1, explanation: "Seven days after Wednesday is Wednesday again; three more days is Saturday." },
  "ver-14": { correctIndex: 0, explanation: "Reluctant means hesitant or unwilling." },
  "num-15": { correctIndex: 1, explanation: "Twelve batches is four times as many as three batches, so the flour increases from 2 cups to 8 cups." },
  "log-09": { correctIndex: 3, explanation: "The Wiks that are Bors may or may not be Dels, so nothing definite follows about Dels and Bors." },
  "ver-15": { correctIndex: 2, explanation: "A painter uses a brush as a primary tool, while a writer uses a pen." },
  "num-16": { correctIndex: 3, explanation: "The pattern alternates multiplying by 2 and subtracting 2. Fourteen doubled is 28." },
  "log-10": { correctIndex: 2, explanation: "M J K L places K after J and M before L, satisfying both rules." },
  "ver-16": { correctIndex: 2, explanation: "Vigorous means strong and energetic; frail is the closest opposite." },
  "num-17": { correctIndex: 2, explanation: "Thirty-five hours multiplied by $18 per hour equals $630." },
  "num-18": { correctIndex: 2, explanation: "Adding 4 gives 3y = 21. Dividing by 3 gives y = 7." },
};
