export const LESSON_PROGRESS_KEY = "aptitude-coach:lesson-progress:v1";

export type LessonCheck = { prompt: string; choices: string[]; correctIndex: number; explanation: string };
export type LessonModule = { title: string; objective: string; instruction: string[]; workedExample: string; trap: string; check: LessonCheck };
export type RemediationLesson = { domain: string; title: string; skill: string; outcome: string; modules: LessonModule[] };

export function remediationLessonFor(skill: string): RemediationLesson {
  const normalized = skill.toLowerCase();
  if (/syllog|ordering|deductive|coding|classification|truth|rule application|logic/.test(normalized)) return logicLesson(skill);
  if (/sentence|vocab|antonym|analogy|word classification|verbal/.test(normalized)) return verbalLesson(skill);
  if (/rotation|reflection|cube|spatial|visual|matri|paper fold|direction/.test(normalized)) return spatialLesson(skill);
  if (/attention|pair|match/.test(normalized)) return comparisonLesson(skill);
  return mathLesson(skill);
}

function module(title: string, objective: string, instruction: string[], workedExample: string, trap: string, prompt: string, choices: string[], correctIndex: number, explanation: string): LessonModule {
  return { title, objective, instruction, workedExample, trap, check: { prompt, choices, correctIndex, explanation } };
}

function logicLesson(skill: string): RemediationLesson {
  return { domain: "Logic", title: `Logic foundations: ${skill}`, skill, outcome: "Translate logic statements into simple constraints, identify what must follow, and reject answers that are merely possible.", modules: [
    module("1. Read the strength of the claim", "Separate all, some, none, if, and only-if statements.", ["ALL A are B means every A belongs inside B.", "SOME A are B guarantees at least one overlap.", "NO A are B forbids overlap.", "If A, then B allows A → B; it does not automatically allow B → A."], "All Rens are Tovs. No Tovs are Meks. Put Rens inside Tovs, then keep the entire Tov group outside Meks. Therefore, no Rens are Meks.", "Reversing a statement: from ‘all Rens are Tovs,’ you cannot conclude that all Tovs are Rens.", "All Lums are Peks. No Peks are Zans. What must be true?", ["No Lums are Zans", "All Zans are Lums", "Some Peks are Lums"], 0, "Lums are contained within Peks, and Peks cannot overlap Zans. Therefore, Lums cannot be Zans."),
    module("2. Build a constraint chain", "Convert ordering and conditional language into a short diagram.", ["Write only the useful relationship: A < B for A before B.", "Join statements that share a term.", "For conditional chains, link A → B and B → C into A → C.", "Test each answer against the completed chain."], "Mira finishes before Lee; Lee finishes before Noor. The chain is Mira < Lee < Noor, so Mira must finish before Noor.", "Trying to hold four or five relationships in memory invites swaps. Externalize the chain.", "If K is selected, M is selected. If M is selected, R is selected. K is selected. What follows?", ["Only M", "M and R", "R is not selected"], 1, "K triggers M, and M triggers R. Both M and R must be selected."),
    module("3. Distinguish must from may", "Use counterexamples to eliminate conclusions that are not guaranteed.", ["Ask: can the premises be true while this answer is false?", "If yes, the answer is not guaranteed.", "Do not import real-world assumptions.", "Prefer the narrow conclusion directly supported by the premises."], "Some Daks are Mors; every Mor is a Tef. The known Daks that are Mors must also be Tefs, so some Daks are Tefs. We cannot say every Dak is a Tef.", "An answer can sound reasonable and still not be logically necessary.", "Every Nib is a Fal. Some Fals are Gors. What is guaranteed?", ["Some Nibs are Gors", "Every Nib is a Fal", "No Nibs are Gors"], 1, "The first premise directly guarantees that every Nib is a Fal. The overlap between Fals and Gors may contain no Nibs."),
    module("4. Execute under CCAT pace", "Use a repeatable 20–30 second decision routine.", ["Classify the item: groups, ordering, conditional, code, or odd-one-out.", "Write one compact diagram or rule.", "Test the choices; do not repeatedly reread the stem.", "If no clean model exists by about 30 seconds, eliminate, choose, and move."], "For ‘No A are B; all C are A,’ sketch C inside A and B outside A. The answer ‘No C are B’ becomes immediate.", "Guessing before translating feels fast but creates confident misses. Spend the first few seconds building the model.", "No Vels are Roks. Every Tam is a Vel. Which conclusion follows?", ["No Tams are Roks", "Some Tams are Roks", "Every Rok is a Tam"], 0, "Tams are inside Vels, and Vels cannot overlap Roks. No Tam can be a Rok."),
  ] };
}

function verbalLesson(skill: string): RemediationLesson {
  return { domain: "Verbal", title: `Verbal foundations: ${skill}`, skill, outcome: "Use sentence structure and word relationships to predict an answer before being distracted by the choices.", modules: [
    module("1. Read structure first", "Identify contrast, cause, support, and tone clues.", ["Circle contrast words such as although, but, despite, and however.", "Notice cause words such as because and therefore.", "Predict whether the blank must be positive, negative, stronger, or weaker.", "Describe the missing idea in plain language before reading choices."], "Although the plan was ambitious, its steps were ___. ‘Although’ signals contrast, so the blank should mean practical or manageable.", "Choosing a familiar word without checking the sentence relationship.", "Although the lecture was brief, it was remarkably ___.", ["concise", "informative", "silent"], 1, "Although creates a contrast between brief duration and substantial value; informative fits that relationship."),
    module("2. Build meaning from roots and context", "Infer unfamiliar vocabulary without needing a perfect definition.", ["Break the word into prefix, root, and suffix.", "Substitute each choice into the sentence.", "Reject choices with the wrong tone or grammatical form.", "Choose the closest contextual meaning, not every possible meaning."], "In ‘a benevolent manager,’ bene means good; benevolent therefore suggests kind or charitable.", "Treating two related words as exact synonyms when their tone differs.", "A person described as meticulous is most likely:", ["careless", "precise", "hurried"], 1, "Meticulous means extremely careful and attentive to detail."),
    module("3. Map relationships", "Solve analogies by writing a precise relationship sentence.", ["State how the first pair relates.", "Keep the direction of the relationship.", "Apply the same sentence to each option.", "Reject broad associations that do not match the relationship."], "Thermometer : temperature means ‘a thermometer measures temperature.’ Scale : weight matches because a scale measures weight.", "Selecting something merely associated with the second word.", "Compass is to direction as clock is to:", ["time", "metal", "circle"], 0, "A compass indicates direction; a clock indicates time."),
    module("4. Timed verbal routine", "Answer accurately without rereading the entire item.", ["Classify: completion, definition, antonym, analogy, or classification.", "Predict the needed meaning or relationship.", "Eliminate by meaning, tone, and grammar.", "Commit once one choice uniquely satisfies the evidence."], "For an antonym, say the target word’s simple meaning, reverse it, then inspect choices.", "Debating between choices before stating what the sentence requires.", "SCARCE is most nearly opposite to:", ["rare", "plentiful", "costly"], 1, "Scarce means limited or insufficient; plentiful is its opposite."),
  ] };
}

function mathLesson(skill: string): RemediationLesson {
  return { domain: "Math", title: `Quantitative foundations: ${skill}`, skill, outcome: "Translate words into one mathematical relationship, estimate the range, and solve with the shortest reliable method.", modules: [
    module("1. Translate the language", "Turn common wording into operations.", ["Of usually means multiply; per means divide or form a rate.", "Percent means out of 100.", "More than and less than describe a difference.", "Assign a variable only when mental arithmetic is not simpler."], "35% of x is 84 becomes 0.35x = 84, so x = 84 ÷ 0.35 = 240.", "Applying a percentage to the wrong base quantity.", "25% of 80 equals:", ["20", "25", "32"], 0, "One quarter of 80 is 20."),
    module("2. Estimate before calculating", "Use answer ranges to detect setup and arithmetic errors.", ["Round inputs to friendly numbers.", "Predict sign, size, and approximate range.", "Calculate exactly once.", "Reject any exact result that conflicts with the estimate."], "19% of 198 is close to 20% of 200, or 40, so an answer near 38 is credible.", "Trusting a clean calculation even when its magnitude makes no sense.", "49% of 202 is closest to:", ["50", "100", "150"], 1, "About half of 202 is about 101, so 100 is the closest choice."),
    module("3. Use answer choices strategically", "Backsolve or compare ratios when direct algebra is slow.", ["For equations, test the middle choice first.", "For proportions, cross-multiply.", "For sequences, inspect differences before complex rules.", "Stop once only one choice satisfies every condition."], "If x + 14 = 31, testing 17 immediately satisfies the relationship.", "Doing long arithmetic when the choices make estimation or backsolving faster.", "If 3 notebooks cost $12, 5 notebooks cost:", ["$15", "$18", "$20"], 2, "Each notebook costs $4, so five cost $20."),
    module("4. Timed quantitative routine", "Balance computation accuracy with the 15-minute limit.", ["Name the operation before touching the numbers.", "Estimate the answer.", "Compute with the shortest reliable method.", "Check the requested quantity and move by 30 seconds if stuck."], "For a percent increase, calculate change ÷ original—not change ÷ new value.", "Solving correctly for an intermediate value that the question did not ask for.", "A value rises from 40 to 50. What is the percent increase?", ["10%", "20%", "25%"], 2, "The increase is 10; 10 ÷ 40 = 25%."),
  ] };
}

function spatialLesson(skill: string): RemediationLesson {
  return { domain: "Spatial", title: `Spatial foundations: ${skill}`, skill, outcome: "Track one visual feature at a time and distinguish rotation, reflection, addition, and movement rules.", modules: [
    module("1. Choose an anchor", "Reduce a figure to one trackable feature.", ["Select an asymmetric corner, dot, notch, or arrow.", "Describe its starting position.", "Apply one transformation at a time.", "Compare the anchor before considering decorative details."], "A top-left dot rotated 90° clockwise moves to top-right.", "Trying to rotate the entire complex figure mentally at once.", "After a 90° clockwise rotation, a mark at top-right moves to:", ["bottom-right", "top-left", "bottom-left"], 0, "Top-right rotates to bottom-right."),
    module("2. Identify the transformation", "Separate rotation from reflection and feature changes.", ["Rotation preserves handedness while changing orientation.", "Reflection reverses handedness.", "Matrix addition combines features from cells.", "Sequences may alternate two independent rules."], "The letter F rotated still has its branches on the same relative side; reflected F reverses them.", "Treating a mirror image as a rotation.", "Which transformation reverses left and right?", ["rotation", "reflection", "translation"], 1, "A reflection reverses handedness and swaps left with right."),
    module("3. Read visual matrices", "Infer a rule across rows and verify it down columns.", ["Compare cell 1 to cell 2, then cell 2 to cell 3.", "Test addition, subtraction, rotation, count, fill, and position.", "Verify the proposed rule in the complete row.", "Apply exactly that rule to the row with the missing cell."], "If ○ plus ● produces ○●, then □ plus ■ should produce □■.", "Inventing a rule that explains only one transition.", "If △, □, pentagon increase sides by one, what follows after □, pentagon?", ["triangle", "hexagon", "circle"], 1, "Square has 4 sides, pentagon 5, so the next figure has 6 sides: a hexagon."),
    module("4. Timed spatial routine", "Make visual decisions without repeated full comparisons.", ["Name the rule in one sentence.", "Track the anchor or count.", "Eliminate choices that violate the primary transformation.", "Use a final orientation check, then commit."], "‘Rotate 90° clockwise and add one dot’ is specific enough to test every option quickly.", "Rechecking every feature after one choice already matches the complete rule.", "An arrow points north, then east, then south. What direction follows?", ["west", "north", "southeast"], 0, "The arrow rotates 90° clockwise each step, so west follows south."),
  ] };
}

function comparisonLesson(skill: string): RemediationLesson {
  return { domain: "Attention to detail", title: `Exact comparison: ${skill}`, skill, outcome: "Compare character pairs with a fixed scan that is both faster and less vulnerable to transpositions.", modules: [
    module("1. Chunk the pair", "Replace whole-string impressions with controlled comparison.", ["Split codes at spaces, hyphens, or every three characters.", "Compare the same chunk on both sides.", "Move left to right without restarting.", "Mark same or different immediately."], "LQ7-483 versus LQ7-438: the first chunk matches; the second contains a transposition, so the pair differs.", "Seeing the same characters and overlooking their order.", "Are AB7-391 and AB7-319 the same?", ["same", "different"], 1, "The final three digits are transposed: 391 versus 319."),
    module("2. Inspect high-risk features", "Catch the differences most likely to be missed.", ["Check repeated letters and digits.", "Check adjacent transpositions.", "Check punctuation and character count.", "Distinguish visually similar symbols such as 0/O and 1/I."], "NP6-219 and NP6-291 differ because the 1 and 9 trade positions.", "Reading the code as a meaningful whole instead of exact characters.", "Are TX4-805 and TX4-805 the same?", ["same", "different"], 0, "Every character, position, and separator matches."),
    module("3. Count without losing place", "Separate classification from tallying.", ["Classify one row at a time.", "Use a finger or visual marker to hold the row.", "Increment the count only for exact matches.", "Do not recount completed rows unless a specific uncertainty remains."], "For S, D, S, S, D classifications, count only S entries: three matches.", "Recounting from the top after every uncertain row.", "How many matches are in S, D, D, S, S?", ["2", "3", "4"], 1, "There are three S entries."),
    module("4. Timed scan", "Maintain a consistent row-by-row cadence.", ["Use the same scan direction on every pair.", "Pause briefly on high-risk chunks, not the entire string.", "Target clean classification rather than maximum eye speed.", "Commit the total once every row has one classification."], "A fixed left-to-right scan is faster over a set because it prevents restarts.", "Rushing easy-looking pairs while overchecking difficult ones creates uneven cadence.", "Which method is most reliable?", ["scan each pair in a fixed direction", "compare the overall appearance", "recount after every row"], 0, "A fixed-direction character scan controls both omissions and unnecessary rereading."),
  ] };
}
