export type SkillLesson = { title: string; method: string[]; example: string; checkpoint: string };

export function lessonFor(skill: string, category?: string): SkillLesson {
  const text = `${skill} ${category ?? ""}`.toLowerCase();
  if (/vocab|sentence|verbal|analogy/.test(text)) return { title: "Context before vocabulary", method: ["Read the sentence without the choices.", "Name the needed meaning and tone.", "Eliminate choices that break grammar or contrast words."], example: "Although the route looked direct, repeated closures made it ___. The contrast points to inefficient or circuitous.", checkpoint: "Can you predict the missing meaning before looking at choices?" };
  if (/pair|match|clerical/.test(text)) return { title: "Exact-match scan", method: ["Compare in fixed chunks from left to right.", "Check punctuation, repeated letters, and digit order.", "Count only after each pair is classified."], example: "AB-731 / AB-713 differs in the last two digits; mark different and move on.", checkpoint: "Did you scan every pair in the same direction?" };
  if (/math|number|arithmetic|ratio|percent|algebra/.test(text)) return { title: "Translate, estimate, solve", method: ["Write the operation the words imply.", "Estimate the answer range.", "Compute once and compare with the choices."], example: "A 20% increase on 45 is about 9 more, so expect 54 before calculating.", checkpoint: "Does your exact answer agree with your estimate?" };
  if (/spatial|rotation|direction|shape/.test(text)) return { title: "Track one feature", method: ["Choose one corner, mark, or direction as an anchor.", "Apply one transformation at a time.", "Compare only the anchored feature to the choices."], example: "270° clockwise equals one 90° counterclockwise turn; simplify before visualizing.", checkpoint: "Can you describe the transformation in one sentence?" };
  if (/logic|pattern|sequence/.test(text)) return { title: "Name the changing rule", method: ["Check differences, ratios, alternation, then interleaving.", "Test the rule on two transitions.", "Predict before opening the choices."], example: "3, 7, 15, 31 follows ×2 + 1, so the next value is 63.", checkpoint: "Does your rule explain every visible transition?" };
  return { title: "Recognize, execute, verify", method: ["Name the question family.", "Choose the shortest reliable method.", "Use one targeted check, then commit."], example: "A clear method prevents both blind rushing and unproductive overchecking.", checkpoint: "What single fact would prove your choice?" };
}
